# Experimentos

## Importando requisitos

In [17]:
import pandas
import os

## Abrindo a planilha

In [4]:
planilha = pandas.read_csv('../Dataset/DataSummary.csv')
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall
...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Filtrando na planilha os datasets selecionados

In [9]:
planilha = planilha[planilha['ID'].between(97, 128)]
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
96,97,EOG,EOGVerticalSignal,362,362,12,1250,0.5580,0.5249 (2),0.5525,0.9144,E. Keogh & H. A. Dau
97,98,Spectro,EthanolLevel,504,500,4,1751,0.7260,0.7180 (1),0.7240,0.7480,A. Bagnall
98,99,Sensor,FreezerRegularTrain,150,2850,2,301,0.1951,0.0930 (1),0.1011,0.5000,REFIT project
99,100,Sensor,FreezerSmallTrain,28,2850,2,301,0.3242,0.3242 (0),0.2411,0.5000,REFIT project
100,101,HRM,Fungi,18,186,18,201,0.1774,0.1774 (0),0.1613,0.8978,W. Fonzi
101,102,Trajectory,GestureMidAirD1,208,130,26,Vary,0.4231,0.3615 (5),0.4308,0.9615,H. A. Dau
102,103,Trajectory,GestureMidAirD2,208,130,26,Vary,0.5077,0.4000 (6),0.3923,0.9615,H. A. Dau
103,104,Trajectory,GestureMidAirD3,208,130,26,Vary,0.6538,0.6231 (1),0.6769,0.9615,H. A. Dau
104,105,Sensor,GesturePebbleZ1,132,172,6,Vary,0.2674,0.1744 (2),0.2093,0.8140,I. Maglogiannis
105,106,Sensor,GesturePebbleZ2,146,158,6,Vary,0.3291,0.2215 (6),0.3291,0.8101,I. Maglogiannis
106,107,Motion,GunPointAgeSpan,135,316,2,150,0.1013,0.0348 (3),0.0823,0.4937,A. Ratanamahatana & E. Keogh
107,108,Motion,GunPointMaleVersusFemale,135,316,2,150,0.0253,0.0253 (0),0.0032,0.4747,A. Ratanamahatana & E. Keogh
108,109,Motion,GunPointOldVersusYoung,136,315,2,150,0.0476,0.0349 (4),0.1619,0.4762,A. Ratanamahatana & E. Keogh
109,110,Device,HouseTwenty,40,119,2,2000,0.3361,0.0588 (33),0.0756,0.4202,E. Keogh & S. Gharghabi
110,111,EPG,InsectEPGRegularTrain,62,249,3,601,0.3213,0.1727 (11),0.1285,0.5261,E. Keogh & S. Gharghabi
111,112,EPG,InsectEPGSmallTrain,17,249,3,601,0.3373,0.3052 (1),0.2651,0.5261,E. Keogh & S. Gharghabi
112,113,Traffic,MelbournePedestrian,1194,2439,10,24,0.1525,0.1845 (1),0.2091,0.8995,H.A. Dau
113,114,Image,MixedShapesRegularTrain,500,2425,5,1024,0.1027,0.0911 (4),0.1584,0.7303,E. Keogh
114,115,Image,MixedShapesSmallTrain,100,2425,5,1024,0.1645,0.1674 (7),0.2202,0.7303,E. Keogh
115,116,Sensor,PickupGestureWiimoteZ,50,50,10,Vary,0.4400,0.3400 (17),0.3400,0.9000,J. Guna
116,117,Hemodynamics,PigAirwayPressure,104,208,52,2000,0.9423,0.9038 (1),0.8942,0.9808,M. Guillame-Bert
117,118,Hemodynamics,PigArtPressure,104,208,52,2000,0.8750,0.8029 (1),0.7548,0.9808,M. Guillame-Bert
118,119,Hemodynamics,PigCVP,104,208,52,2000,0.9183,0.8413 (11),0.8462,0.9808,M. Guillame-Bert
119,120,Device,PLAID,537,537,11,Vary,0.4767,0.1657 (12),0.1639,0.8380,P. Schafer
120,121,Power,PowerCons,180,180,2,144,0.0667,0.0778 (3),0.1222,0.5000,"EDF R&D, France"
121,122,Spectrum,Rock,20,50,4,2844,0.1600,0.1600 (0),0.4000,0.5800,Y. Zhu
122,123,Spectrum,SemgHandGenderCh2,300,600,2,1500,0.2383,0.1550 (1),0.1983,0.3500,C.-C. M. Yeh
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Realizando experimentos no dataset da primeira linha da tabela

Obtendo o caminho do dataset de exemplo

In [16]:
dataset_exemplo = planilha.iloc[0]['Name']
dataset_exemplo

'EOGVerticalSignal'

In [19]:
dataset_dirname = os.path.join('../Dataset/UCRArchive_2018', dataset_exemplo)
dataset_dirname

'../Dataset/UCRArchive_2018/EOGVerticalSignal'

In [21]:
caminho_arquivo_treino = os.path.join(dataset_dirname, '{}_TRAIN.tsv'.format(dataset_exemplo))
caminho_arquivo_treino

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TRAIN.tsv'

In [22]:
caminho_arquivo_teste = os.path.join(dataset_dirname, '{}_TEST.tsv'.format((dataset_exemplo)))
caminho_arquivo_teste

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TEST.tsv'

Abrindo datasets

In [31]:
dataset_exemplo_treino = pandas.read_csv(caminho_arquivo_treino, sep='\t', header=None)
dataset_exemplo_treino

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,-5.70320,-5.89550,-5.88780,-6.08000,-6.17230,-6.26460,-6.2568,-6.1491,-6.4414,...,-113.3100,-113.4100,-113.50000,-114.390000,-114.4800,-113.77000,-113.0700,-113.1600,-112.8500,-112.9400
1,1,-2.18020,-2.30860,-2.33690,-2.36520,-2.39360,-2.02190,-2.0502,-2.0786,-2.5069,...,108.3900,108.5600,108.53000,108.500000,108.4700,108.45000,108.4200,108.3900,108.1600,108.1300
2,1,6.70950,6.52680,6.34420,6.16160,5.97900,5.79640,5.6137,4.5311,2.7485,...,-34.9360,-35.1190,-35.30100,-35.484000,-35.6660,-34.94900,-35.1320,-35.3140,-34.5970,-34.7800
3,1,-0.91251,-0.72238,-0.53226,-0.74213,-0.95201,-1.16190,-1.5718,-1.7816,-1.1915,...,-173.8600,-174.0700,-173.68000,-173.890000,-174.7000,-174.71000,-174.9200,-175.1300,-174.7400,-174.3500
4,1,-5.44400,-5.32610,-4.10820,-3.69020,-3.57230,-3.45440,-3.0364,-2.6185,-2.5006,...,2.0864,1.8044,1.92230,2.040200,2.1582,2.27610,2.3940,2.5119,2.6299,2.7478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,-4.32250,-2.52830,-2.83410,-2.83980,-2.84560,-2.85130,-4.3571,-4.3629,-4.3686,...,-2.1725,-1.3783,-0.08404,-0.089806,1.5044,-0.10134,-1.1071,-1.1129,-1.3186,-1.3244
358,12,-5.91600,-5.90050,-6.68500,-7.76950,-7.75400,-7.73850,-6.6230,-6.6075,-6.5920,...,32.0100,28.3260,25.44100,27.857000,32.0720,32.08800,31.9030,27.9190,27.9340,27.9500
359,12,2.66670,2.60940,2.55220,4.59490,1.63760,0.38033,2.4231,4.0658,2.3085,...,-42.8540,-42.9110,-42.96900,-43.026000,-44.3830,-45.84000,-44.4980,-44.5550,-44.6120,-47.1690
360,12,-1.22680,-1.24790,1.63100,1.50990,1.38880,3.16770,3.0465,2.9254,3.4043,...,-97.5090,-94.3310,-97.75200,-94.573000,-94.6940,-94.81500,-94.9360,-98.0570,-102.5800,-102.7000
361,12,-11.76000,-9.95780,-12.15500,-12.25300,-10.25000,-12.74800,-10.4450,-12.1430,-11.8400,...,-100.6800,-100.7800,-100.07000,-100.170000,-101.0700,-100.37000,-100.4600,-101.3600,-101.4600,-100.7600

In [32]:
dataset_exemplo_teste = pandas.read_csv(caminho_arquivo_teste, sep='\t', header=None)
dataset_exemplo_teste

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,2.67520,2.68930,3.2034,4.01750,3.93150,3.94560,3.55970,3.87380,3.48790,...,-394.470,-392.450,-391.240,-390.830,-390.710,-390.900,-390.980,-390.870,-390.850,-390.740
1,1,6.84840,6.17140,5.6944,5.31730,5.14030,4.96330,4.18620,3.60920,2.73220,...,-145.670,-144.850,-144.220,-143.900,-143.680,-143.860,-143.530,-144.210,-144.790,-144.960
2,1,-4.91380,-4.87180,-4.8298,-4.98790,-5.14590,-4.50390,-4.66190,-3.72000,-3.57800,...,-169.270,-169.430,-169.590,-169.140,-169.100,-169.260,-169.420,-169.980,-170.730,-170.890
3,1,18.27800,18.29000,18.3020,18.31400,18.32600,19.13800,19.15000,19.86200,19.17400,...,308.330,307.840,308.350,307.670,307.380,308.290,308.300,308.310,307.830,307.840
4,1,-6.26350,-6.28940,-6.0153,-5.34120,-5.46710,-6.09300,-6.71890,-6.34470,-6.47060,...,39.229,38.503,38.077,37.551,37.425,36.499,36.374,37.048,36.922,36.796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,2.02960,1.62900,1.2284,0.92786,0.72729,0.42672,0.42615,0.12558,0.12501,...,-12.375,-14.576,-14.576,-12.577,-12.577,-11.278,-11.279,-12.579,-11.280,-12.580
358,12,1.39790,1.59650,1.6951,0.89369,1.09230,1.29090,0.28948,0.08808,0.28668,...,132.660,132.460,132.660,132.850,133.450,133.950,133.850,134.050,133.850,134.350
359,12,1.90450,1.74240,1.8803,3.41830,2.15620,1.99420,2.13210,3.97010,4.10800,...,93.154,92.992,92.630,92.068,90.606,89.744,89.282,89.020,88.758,88.896
360,12,17.80400,16.97900,16.5540,16.02900,15.70400,15.07800,14.75300,13.22800,11.50300,...,-419.660,-419.990,-420.310,-420.040,-420.060,-420.390,-420.510,-420.840,-421.160,-421.490
361,12,-0.10837,0.44276,1.4939,2.34500,2.29610,2.94730,2.89840,2.84950,2.10070,...,-103.210,-103.860,-103.910,-103.950,-104.300,-104.050,-104.100,-104.450,-104.500,-104.950

### Aplicando algoritmos nos datasets

Importando algoritmos

In [33]:
from app.model.DynamicTimeWarping import DynamicTimeWarping
from app.model.DerivativeDynamicTimeWarping import DerivativeDynamicTimeWarping
from app.model.LongestCommonSubsequence import LongestCommonSubsequence
from app.model.SoftDynamicTimeWarping import SoftDynamicTimeWarping

Obtendo conjuntos de treino e teste: x e y

In [40]:
x_train = []
for linha in dataset_exemplo_treino.iloc[:, 1:].values:
    x_train.append(linha)
x_train

[array([  -5.7032,   -5.8955,   -5.8878, ..., -113.16  , -112.85  ,
        -112.94  ], shape=(1250,)),
 array([ -2.1802,  -2.3086,  -2.3369, ..., 108.39  , 108.16  , 108.13  ],
       shape=(1250,)),
 array([  6.7095,   6.5268,   6.3442, ..., -35.314 , -34.597 , -34.78  ],
       shape=(1250,)),
 array([  -0.91251,   -0.72238,   -0.53226, ..., -175.13   , -174.74   ,
        -174.35   ], shape=(1250,)),
 array([-5.444 , -5.3261, -4.1082, ...,  2.5119,  2.6299,  2.7478],
       shape=(1250,)),
 array([-29.207, -28.574, -28.241, ..., 102.63 , 102.36 , 102.9  ],
       shape=(1250,)),
 array([ -17.494,  -16.756,  -16.817, ..., -548.16 , -548.92 , -549.38 ],
       shape=(1250,)),
 array([ -37.921,  -35.45 ,  -32.58 , ..., -921.33 , -922.56 , -923.79 ],
       shape=(1250,)),
 array([ -9.0291,  -9.2402,  -9.2512, ..., -63.172 , -62.683 , -63.194 ],
       shape=(1250,)),
 array([-1.3589, -1.1494, -0.8399, ..., 64.361 , 64.27  , 64.18  ],
       shape=(1250,)),
 array([  10.287 ,    4.7215,    3.3557, ..., -139.31  , -139.78  ,
        -140.44  ], shape=(1250,)),
 array([-2.4946, -2.4378, -2.6811, ..., 28.249 , 28.305 , 27.462 ],
       shape=(1250,)),
 array([  0.89541,   0.71393,  -0.26754, ..., -24.406  , -24.387  ,
        -24.469  ], shape=(1250,)),
 array([  -3.7158,   -3.7703,   -4.1249, ..., -103.84  , -103.89  ,
        -103.94  ], shape=(1250,)),
 array([ -1.2036,  -1.0807,  -1.0579, ..., -36.95  , -37.527 , -38.205 ],
       shape=(1250,)),
 array([-1.2327, -1.1678, -1.103 , ..., 30.056 , 29.921 , 29.986 ],
       shape=(1250,)),
 array([ 4.6693,  4.467 ,  2.7648, ..., 94.28  , 94.378 , 93.376 ],
       shape=(1250,)),
 array([  1.6541,   1.6378,   1.6214, ..., -93.948 , -93.964 , -94.381 ],
       shape=(1250,)),
 array([ 2.8486,  2.9415,  2.3345, ..., 57.016 , 57.109 , 56.902 ],
       shape=(1250,)),
 array([-2.8073, -2.7814, -2.7555, ..., 12.394 , 12.22  , 12.246 ],
       shape=(1250,)),
 array([   7.7653,    7.5622,    7.3592, ..., -335.54  , -335.74  ,
        -336.45  ], shape=(1250,)),
 array([ -2.32  ,  -2.0007,  -1.5814, ..., -56.249 , -56.23  , -57.11  ],
       shape=(1250,)),
 array([  0.19354,   0.21478,   0.23602, ..., -85.119  , -85.498  ,
        -85.477  ], shape=(1250,)),
 array([   3.9657,    3.9229,    2.88  , ..., -125.9   , -125.94  ,
        -125.78  ], shape=(1250,)),
 array([  6.7349,   6.025 ,   6.015 , ..., -73.442 , -73.452 , -73.462 ],
       shape=(1250,)),
 array([ 0.72342 , -0.011602, -1.0466  , ...,  2.9471  ,  2.3121  ,
         2.3771  ], shape=(1250,)),
 array([  5.172 ,   5.1848,   5.1976, ..., -21.842 , -21.829 , -21.816 ],
       shape=(1250,)),
 array([  2.093 ,   2.0593,   2.0257, ..., -98.944 , -98.978 , -99.011 ],
       shape=(1250,)),
 array([ -3.5158,  -3.7706,  -3.6254, ..., -80.623 , -81.378 , -80.433 ],
       shape=(1250,)),
 array([ -1.11  ,  -1.0706,  -1.0313, ..., -35.919 , -35.48  , -35.441 ],
       shape=(1250,)),
 array([  7.2369,   7.2502,   6.2636, ..., -38.213 , -38.2   , -37.486 ],
       shape=(1250,)),
 array([  5.0322,   6.3304,   6.3286, ..., -62.302 , -63.103 , -63.105 ],
       shape=(1250,)),
 array([   5.6273,    5.5711,    5.3148, ..., -108.43  , -107.59  ,
        -107.65  ], shape=(1250,)),
 array([-8.4822e-02, -4.1644e-01, -4.4806e-01, ..., -1.2161e+02,
        -1.2244e+02, -1.2328e+02], shape=(1250,)),
 array([ -1.5634,  -1.5419,  -1.7205, ..., -51.406 , -51.685 , -51.664 ],
       shape=(1250,)),
 array([  2.5613,   2.58  ,   1.4987, ..., -77.418 , -77.699 , -77.681 ],
       shape=(1250,)),
 array([  4.3838,   4.4114,   4.4391, ..., -23.855 , -23.827 , -23.1   ],
       shape=(1250,)),
 array([ -1.0137 ,  -0.97273,  -0.23179, ..., -26.859  , -26.918  ,
        -26.877  ], shape=(1250,)),
 array([   0.53834,    0.14059,    0.14284, ..., -103.65   , -103.65   ,
        -104.25   ], shape=(1250,)),
 array([ -3.0621,  -3.0652,  -3.0684, ..., -56.647 , -57.05  , -57.053 ],
       shape=(1250,)),
 array([-3.0904, -3.1045, -2.3186, ..., 13.037 , 13.023 , 13.009 ],
       shape=(1250,)),
 array([  0.38848,   1.169  ,   0.54944, ..., 200.95   , 201.03   ,
        201.11   ], shape=(1250,)),
 array([ 2.7201,  2.6935,  2.9668, ..., 84.998 , 83.871 , 83.544 ],
       shape=(1250,)),
 array([  4.6044,   3.8813,   4.8581, ..., 191.54  , 189.71  , 190.09  ],
       shape=(1250,)),
 array([ -2.7756,  -1.8768,  -1.978 , ..., -81.306 , -80.407 , -79.309 ],
       shape=(1250,)),
 array([ -0.40992,  -0.71793,  -0.62595, ..., 212.59   , 214.29   ,
        214.78   ], shape=(1250,)),
 array([1.1328e-01, 1.3159e-01, 1.4990e-01, ..., 1.2744e+02, 1.2746e+02,
        1.2578e+02], shape=(1250,)),
 array([ 0.57003,  0.47643, -0.61718, ..., 31.147  , 31.953  , 32.659  ],
       shape=(1250,)),
 array([  3.7137,   3.9027,   3.8916, ..., 112.44  , 112.43  , 112.42  ],
       shape=(1250,)),
 array([ 2.3734 ,  1.1585 ,  0.64369, ..., 58.446  , 57.531  , 57.516  ],
       shape=(1250,)),
 array([  6.5663,   6.0079,   4.4494, ..., -20.801 , -19.86  , -19.818 ],
       shape=(1250,)),
 array([  3.062 ,   3.1191,   3.1762, ..., -51.3   , -50.242 , -50.185 ],
       shape=(1250,)),
 array([  -7.8462,   -7.8259,   -7.8056, ..., -111.14  , -111.12  ,
        -110.9   ], shape=(1250,)),
 array([ -0.73689,  -0.69918,  -0.66147, ..., -73.017  , -72.979  ,
        -73.941  ], shape=(1250,)),
 array([  2.3936,   2.7034,   2.7133, ..., -70.359 , -70.349 , -69.539 ],
       shape=(1250,)),
 array([   1.3391 ,    1.271  ,    0.70302, ..., -192.08   , -192.14   ,
        -192.21   ], shape=(1250,)),
 array([   3.1412,    2.338 ,    1.4349, ..., -133.76  , -134.07  ,
        -134.07  ], shape=(1250,)),
 array([  2.5622,   2.5765,   1.3907, ..., -99.816 , -99.802 , -98.987 ],
       shape=(1250,)),
 array([-3.9507e-01,  2.4428e-01,  1.8364e-01, ..., -1.9682e+02,
        -1.9688e+02, -1.9724e+02], shape=(1250,)),
 array([-2.8991e-02, -9.1370e-02, -1.5375e-01, ..., -2.1242e+02,
        -2.1248e+02, -2.1254e+02], shape=(1250,)),
 array([ 8.2866,  7.2272,  5.7677, ..., 40.321 , 40.362 , 40.102 ],
       shape=(1250,)),
 array([-3.7571, -3.676 , -3.0949, ...,  6.3561,  6.9372,  7.1183],
       shape=(1250,)),
 array([ 7.3777e-01, -6.7624e-02,  2.6984e-02, ...,  4.4913e+01,
         4.5008e+01,  4.4503e+01], shape=(1250,)),
 array([-3.3822, -2.9661, -2.05  , ...,  3.4876,  4.1036,  4.1197],
       shape=(1250,)),
 array([ -3.1657,  -3.1896,  -3.2135, ..., -33.232 , -33.256 , -33.28  ],
       shape=(1250,)),
 array([ -1.4594,  -1.4318,  -1.4042, ..., -10.45  ,  -8.5224,  -8.4948],
       shape=(1250,)),
 array([ -1.0013,  -1.977 ,  -1.5526, ..., 101.72  , 101.85  , 102.47  ],
       shape=(1250,)),
 array([-4.3564, -4.3083, -4.2601, ..., 29.412 , 29.461 , 28.809 ],
       shape=(1250,)),
 array([  4.9121,   4.8702,   4.8282, ..., -82.889 , -82.931 , -82.973 ],
       shape=(1250,)),
 array([ -5.4224,  -5.5006,  -4.8788, ..., -44.119 , -44.197 , -45.375 ],
       shape=(1250,)),
 array([ -1.5977,  -1.5536,  -1.8095, ..., -53.021 , -52.977 , -52.932 ],
       shape=(1250,)),
 array([ -0.34856,  -1.2043 ,  -2.1601 , ..., -35.615  , -35.57   ,
        -35.526  ], shape=(1250,)),
 array([   0.72131,    0.63443,    0.54755, ..., -190.21   , -190.3    ,
        -190.39   ], shape=(1250,)),
 array([ 2.1856,  3.0696,  3.1536, ..., 52.95  , 53.934 , 52.918 ],
       shape=(1250,)),
 array([  6.7476,   6.6057,   6.5638, ..., -20.105 , -20.047 , -19.988 ],
       shape=(1250,)),
 array([  24.641,   24.174,   23.506, ..., -831.35 , -832.32 , -832.98 ],
       shape=(1250,)),
 array([  6.7519,   6.8051,   6.3583, ..., -63.593 , -63.54  , -63.686 ],
       shape=(1250,)),
 array([ 3.8874,  3.9919,  4.0963, ..., 19.594 , 20.298 , 20.403 ],
       shape=(1250,)),
 array([0.83676, 0.92257, 1.0084 , ..., 8.1448 , 8.2306 , 7.3164 ],
       shape=(1250,)),
 array([  -2.599 ,   -2.7244,   -2.8498, ..., -277.12  , -277.75  ,
        -277.88  ], shape=(1250,)),
 array([  3.9334,   3.8694,   3.8054, ..., -40.928 , -40.992 , -42.356 ],
       shape=(1250,)),
 array([ 1.2302 ,  0.30625,  1.1823 , ..., 34.856  , 34.932  , 35.908  ],
       shape=(1250,)),
 array([-0.36614, -0.95974, -1.3533 , ..., -6.8839 , -6.0775 , -6.0711 ],
       shape=(1250,)),
 array([-0.24792, -0.1886 , -0.12927, ..., 24.73   , 24.789  , 24.749  ],
       shape=(1250,)),
 array([ 4.9166,  4.9454,  4.9743, ..., -2.9117, -2.8828, -2.354 ],
       shape=(1250,)),
 array([ 3.0575,  3.1386,  2.8198, ..., 16.441 , 16.022 , 15.603 ],
       shape=(1250,)),
 array([  1.0089 ,  -0.12901,  -0.16691, ..., -25.552  , -25.59   ,
        -25.628  ], shape=(1250,)),
 array([ 2.5906,  2.6725,  2.7544, ..., 23.729 , 24.111 , 23.892 ],
       shape=(1250,)),
 array([ 2.3003,  1.924 ,  1.9476, ..., -7.1955, -7.1719, -7.1482],
       shape=(1250,)),
 array([ 2.0296,  2.1263,  2.2229, ..., 80.934 , 81.031 , 81.128 ],
       shape=(1250,)),
 array([ 4.6423,  6.9364,  5.0306, ..., 91.107 , 91.901 , 91.996 ],
       shape=(1250,)),
 array([  4.4885,   4.5501,   4.4117, ..., -48.918 , -48.856 , -48.794 ],
       shape=(1250,)),
 array([  -1.6688,   -1.6515,   -2.3341, ..., -115.34  , -115.32  ,
        -115.3   ], shape=(1250,)),
 array([  1.9376 ,  -0.42269,  -0.38296, ..., -40.723  , -40.683  ,
        -40.743  ], shape=(1250,)),
 array([  3.752 ,   4.8848,   4.6176, ..., -99.522 , -99.489 , -99.456 ],
       shape=(1250,)),
 array([ -1.649  ,  -1.0017 ,  -0.55438, ..., -94.648  , -95.101  ,
        -95.054  ], shape=(1250,)),
 array([ 1.1038 ,  1.2192 , -0.26532, ..., 91.653  , 91.768  , 91.883  ],
       shape=(1250,)),
 array([  -6.42  ,   -6.4473,   -6.4745, ..., -144.86  , -144.89  ,
        -145.71  ], shape=(1250,)),
 array([  2.514 ,   3.165 ,   4.2161, ..., -47.123 , -47.072 , -47.621 ],
       shape=(1250,)),
 array([  5.6324,   5.6084,   5.7845, ..., -92.919 , -92.943 , -92.967 ],
       shape=(1250,)),
 array([ -4.0283,  -4.7058,  -4.5834, ..., 164.15  , 164.87  , 165.    ],
       shape=(1250,)),
 array([ 0.96167,  0.92542,  0.98916, ..., 73.156  , 73.22   , 73.284  ],
       shape=(1250,)),
 array([  2.1492,   2.0958,   1.4424, ..., -82.122 , -81.975 , -81.628 ],
       shape=(1250,)),
 array([ 2.6223,  2.7014,  2.7804, ..., 43.445 , 43.524 , 43.603 ],
       shape=(1250,)),
 array([ -38.172,  -37.24 ,  -35.108, ..., -153.42 , -153.99 , -154.36 ],
       shape=(1250,)),
 array([ 0.44798,  0.29103, -0.16593, ..., 25.026  , 25.169  , 25.312  ],
       shape=(1250,)),
 array([-2.5535, -2.4923, -2.7311, ..., -6.1323, -6.0711, -6.0099],
       shape=(1250,)),
 array([ -4.3329,  -4.3362,  -4.3394, ..., -48.97  , -48.973 , -48.977 ],
       shape=(1250,)),
 array([ -1.0199 ,  -0.89427,  -0.7686 , ..., 108.59   , 108.91   ,
        109.04   ], shape=(1250,)),
 array([ 0.7741 ,  0.80111,  1.6281 , ..., 39.551  , 39.178  , 39.205  ],
       shape=(1250,)),
 array([ -3.6632,  -3.5848,  -3.8064, ..., -27.979 , -28.    , -27.922 ],
       shape=(1250,)),
 array([-2.7033 , -0.58008, -0.45684, ..., 93.58   , 93.704  , 93.827  ],
       shape=(1250,)),
 array([-0.39133, -0.39438, -0.39742, ...,  6.0119 ,  6.0089 ,  6.0058 ],
       shape=(1250,)),
 array([-3.2018, -3.2212, -3.6407, ..., -2.6305, -2.0499, -2.0693],
       shape=(1250,)),
 array([  0.52096,   0.47278,   0.42459, ..., -52.361  , -52.409  ,
        -52.457  ], shape=(1250,)),
 array([2.2266, 2.2569, 1.8871, ..., 2.8126, 2.8429, 2.8731], shape=(1250,)),
 array([  3.415 ,   3.3924,   3.3698, ..., -87.636 , -86.359 , -86.381 ],
       shape=(1250,)),
 array([  8.2712,   8.2907,   8.3102, ..., -20.442 , -20.423 , -21.103 ],
       shape=(1250,)),
 array([-23.994, -23.865, -23.836, ..., -73.164, -73.135, -73.106],
       shape=(1250,)),
 array([-0.72208,  0.59658, -0.68477, ..., 49.14   , 49.159  , 49.177  ],
       shape=(1250,)),
 array([ -7.7795,  -7.7338,  -7.588 , ..., -37.753 , -37.107 , -37.062 ],
       shape=(1250,)),
 array([-17.382, -17.367, -17.351, ..., -64.183, -64.467, -64.451],
       shape=(1250,)),
 array([  9.1938,   5.803 ,   5.4123, ..., -41.265 , -41.256 , -41.247 ],
       shape=(1250,)),
 array([ -7.2938,  -7.2428,  -2.5917, ..., -23.629 , -23.578 , -23.527 ],
       shape=(1250,)),
 array([  0.10216,   0.84449,   0.88682, ..., -87.715  , -87.772  ,
        -87.73   ], shape=(1250,)),
 array([ -3.1578,  -3.1491,  -3.1405, ..., -59.375 , -59.366 , -56.657 ],
       shape=(1250,)),
 array([ -1.6742,  -1.6634,  -1.6527, ..., -80.326 , -78.516 , -79.705 ],
       shape=(1250,)),
 array([10.897, 11.031, 11.166, ..., 57.297, 57.431, 54.666], shape=(1250,)),
 array([-9.8208, -9.4261, -9.3313, ..., 59.057 , 60.552 , 59.247 ],
       shape=(1250,)),
 array([ -3.8343,  -3.8689,  -3.9036, ..., -68.237 , -68.272 , -68.306 ],
       shape=(1250,)),
 array([-22.696, -21.679, -18.462, ..., -99.559, -99.542, -99.525],
       shape=(1250,)),
 array([  -6.2546,   -6.2738,   -6.293 , ..., -113.01  , -113.03  ,
        -113.05  ], shape=(1250,)),
 array([   5.7178,    5.6518,    5.5859, ..., -213.67  , -213.74  ,
        -214.1   ], shape=(1250,)),
 array([  -8.6547,   -8.7414,   -8.8281, ..., -240.97  , -240.75  ,
        -239.64  ], shape=(1250,)),
 array([   4.6324,    4.4336,    6.6348, ..., -414.09  , -414.28  ,
        -414.48  ], shape=(1250,)),
 array([  -4.8971,   -5.8404,   -5.8838, ..., -160.96  , -161.    ,
        -161.05  ], shape=(1250,)),
 array([   0.54428,    0.4257 ,    0.30712, ..., -223.43   , -224.05   ,
        -224.16   ], shape=(1250,)),
 array([   0.71684,    0.74891,    0.48097, ..., -127.5    , -127.86   ,
        -128.63   ], shape=(1250,)),
 array([   0.6455 ,    0.57249,   -2.2005 , ..., -249.     , -245.98   ,
        -246.05   ], shape=(1250,)),
 array([ -14.29 ,  -14.286,  -13.382, ..., -197.65 , -197.05 , -197.04 ],
       shape=(1250,)),
 array([ -13.704,  -11.702,  -11.099, ..., -233.12 , -233.22 , -233.92 ],
       shape=(1250,)),
 array([ -36.173,  -36.108,  -35.442, ..., -114.39 , -118.62 , -121.96 ],
       shape=(1250,)),
 array([ -8.8851,  -8.6132,  -7.8413, ..., -91.475 , -91.503 , -91.531 ],
       shape=(1250,)),
 array([  -1.1141 ,   -1.1508 ,   -0.78756, ..., -109.24   , -109.28   ,
        -109.32   ], shape=(1250,)),
 array([-10.841, -11.884, -11.927, ..., -63.416, -63.46 , -63.503],
       shape=(1250,)),
 array([  2.5672,   1.6379,   1.6087, ..., -83.703 , -83.532 , -85.562 ],
       shape=(1250,)),
 array([  2.1886,   2.4178,   2.647 , ..., 106.71  , 107.44  , 107.17  ],
       shape=(1250,)),
 array([ -8.3386,  -8.2828,  -8.2271, ..., -18.229 , -19.274 , -19.218 ],
       shape=(1250,)),
 array([  39.323,   35.171,   29.719, ..., -180.28 , -180.33 , -181.18 ],
       shape=(1250,)),
 array([  48.152,   46.146,   45.939, ..., -299.76 , -299.96 , -301.67 ],
       shape=(1250,)),
 array([   6.5495,    7.6045,    7.4595, ..., -250.34  , -250.49  ,
        -249.13  ], shape=(1250,)),
 array([   4.4491,    4.3735,    4.298 , ..., -239.49  , -239.56  ,
        -240.44  ], shape=(1250,)),
 array([  -6.6009,   -6.5602,   -5.5196, ..., -125.91  , -124.17  ,
        -124.13  ], shape=(1250,)),
 array([  -0.41975,    0.73317,    0.68609, ..., -189.93   , -190.68   ,
        -190.03   ], shape=(1250,)),
 array([ 28.91 ,  26.209,  23.209, ..., -91.496, -91.997, -91.997],
       shape=(1250,)),
 array([  -3.6854,   -3.3265,   -3.4675, ..., -279.74  , -279.88  ,
        -280.02  ], shape=(1250,)),
 array([ -13.922,  -12.019,  -12.117, ..., -237.55 , -235.95 , -236.05 ],
       shape=(1250,)),
 array([  -0.59204,   -0.76515,    0.66175, ..., -282.96   , -283.13   ,
        -281.9    ], shape=(1250,)),
 array([-7.3157, -6.8154, -6.7151, ...,  4.8578,  4.9581,  5.6584],
       shape=(1250,)),
 array([   6.936 ,    6.7777,    5.1194, ..., -229.57  , -229.73  ,
        -229.89  ], shape=(1250,)),
 array([-17.104, -15.431, -13.759, ..., 116.08 , 116.05 , 116.03 ],
       shape=(1250,)),
 array([  0.72105,   0.71849,   0.71594, ..., 147.83   , 145.83   ,
        145.63   ], shape=(1250,)),
 array([  4.2644,   4.0843,   2.5042, ..., 163.09  , 161.21  , 162.13  ],
       shape=(1250,)),
 array([ -0.598  ,  -0.61711,   0.56378, ..., 159.67   , 159.65   ,
        159.53   ], shape=(1250,)),
 array([ 0.51922,  0.47969, -2.1598 , ..., 94.936  , 95.896  , 96.857  ],
       shape=(1250,)),
 array([  4.2988,   4.1758,   4.2528, ..., 233.66  , 233.74  , 232.62  ],
       shape=(1250,)),
 array([-10.071, -10.955, -11.039, ...,  62.033,  61.949,  61.865],
       shape=(1250,)),
 array([ -4.5003,  -4.489 ,  -4.4778, ..., 143.83  , 143.84  , 142.15  ],
       shape=(1250,)),
 array([ -8.875 ,  -8.9055,  -8.4359, ..., 139.64  , 139.61  , 139.58  ],
       shape=(1250,)),
 array([  6.8592,   4.1639,   2.6686, ..., 211.    , 212.4   , 212.41  ],
       shape=(1250,)),
 array([  -2.9802,   -3.0678,   -3.1553, ..., -295.5   , -295.59  ,
        -296.18  ], shape=(1250,)),
 array([  -8.8585,   -8.4207,   -7.9829, ..., -179.62  , -179.58  ,
        -179.55  ], shape=(1250,)),
 array([ -10.534,  -10.555,  -10.577, ..., -213.25 , -212.67 , -212.69 ],
       shape=(1250,)),
 array([ 4.2174e-01,  4.3276e-01,  4.3775e-02, ..., -1.8114e+02,
        -1.8273e+02, -1.8272e+02], shape=(1250,)),
 array([ -18.834,  -18.801,  -18.768, ..., -171.62 , -170.49 , -170.46 ],
       shape=(1250,)),
 array([  18.96 ,   15.535,   14.811, ..., -205.15 , -204.87 , -204.9  ],
       shape=(1250,)),
 array([  -4.4627,   -4.4655,   -4.4683, ..., -179.25  , -179.25  ,
        -176.95  ], shape=(1250,)),
 array([  11.782 ,    8.1523,    8.1226, ..., -192.46  , -192.49  ,
        -192.52  ], shape=(1250,)),
 array([  -5.159 ,   -5.081 ,   -5.0031, ..., -103.7   , -105.23  ,
        -105.15  ], shape=(1250,)),
 array([  19.239 ,    7.9648,    4.6901, ..., -383.19  , -383.36  ,
        -383.54  ], shape=(1250,)),
 array([  -3.1447,   -3.2856,   -3.4265, ..., -128.34  , -128.48  ,
        -128.63  ], shape=(1250,)),
 array([-18.293, -18.121, -18.15 , ..., 223.78 , 225.05 , 225.22 ],
       shape=(1250,)),
 array([   8.4138,    5.9699,    5.6259, ..., -333.48  , -333.83  ,
        -334.17  ], shape=(1250,)),
 array([ -1.6362 ,  -0.85704,  -0.97784, ..., -96.767  , -99.488  ,
        -98.309  ], shape=(1250,)),
 array([ -3.5738,  -3.6752,  -3.7766, ..., -54.555 , -54.656 , -52.658 ],
       shape=(1250,)),
 array([ -7.074 ,  -7.1345,  -7.1951, ..., -57.436 , -57.496 , -57.557 ],
       shape=(1250,)),
 array([-0.067955,  0.23561 ,  0.03917 , ..., 35.275   , 35.978   ,
        36.982   ], shape=(1250,)),
 array([ -3.3087,  -4.2786,  -4.3486, ..., -62.905 , -63.775 , -65.145 ],
       shape=(1250,)),
 array([  0.70378,   0.62363,   0.84348, ..., -39.646  , -40.426  ,
        -39.807  ], shape=(1250,)),
 array([ -8.4299,  -8.4875,  -8.5451, ..., -38.106 , -38.163 , -38.221 ],
       shape=(1250,)),
 array([  30.953,   28.723,   27.692, ..., -190.73 , -190.86 , -190.99 ],
       shape=(1250,)),
 array([  -5.7028,   -5.7269,   -4.651 , ..., -114.08  , -115.01  ,
        -113.93  ], shape=(1250,)),
 array([ -2.2022 ,  -0.73975,  -0.27726, ..., -84.371  , -81.908  ,
        -81.946  ], shape=(1250,)),
 array([  -4.3618,   -2.3324,   -2.4029, ..., -150.01  , -150.08  ,
        -149.95  ], shape=(1250,)),
 array([ 8.1358e-02, -6.8494e-02, -2.1835e-01, ..., -2.2458e+02,
        -2.2723e+02, -2.2738e+02], shape=(1250,)),
 array([-13.652, -12.929, -12.906, ..., -83.191, -83.168, -83.146],
       shape=(1250,)),
 array([  16.636,   15.687,   15.638, ..., -145.76 , -145.81 , -145.86 ],
       shape=(1250,)),
 array([  -3.5549,   -3.5915,   -3.6281, ..., -169.25  , -168.69  ,
        -169.32  ], shape=(1250,)),
 array([  -0.56759,   -0.61123,   -0.65486, ..., -130.48   , -130.23   ,
        -128.97   ], shape=(1250,)),
 array([ -10.805 ,   -7.9008,   -7.8963, ..., -122.24  , -122.24  ,
        -122.23  ], shape=(1250,)),
 array([ -10.386 ,  -10.471 ,   -8.6561, ..., -122.8   , -120.88  ,
        -122.37  ], shape=(1250,)),
 array([   0.61385,    0.53915,    0.46445, ..., -161.44   , -161.52   ,
        -160.89   ], shape=(1250,)),

In [43]:
y_train = []
for linha in dataset_exemplo_treino.iloc[:, 0].values:
    y_train.append(linha)
y_train

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12)]

In [42]:
x_test = []
for linha in dataset_exemplo_teste.iloc[:, 1:].values:
    x_test.append(linha)
x_test

[array([   2.6752,    2.6893,    3.2034, ..., -390.87  , -390.85  ,
        -390.74  ], shape=(1250,)),
 array([   6.8484,    6.1714,    5.6944, ..., -144.21  , -144.79  ,
        -144.96  ], shape=(1250,)),
 array([  -4.9138,   -4.8718,   -4.8298, ..., -169.98  , -170.73  ,
        -170.89  ], shape=(1250,)),
 array([ 18.278,  18.29 ,  18.302, ..., 308.31 , 307.83 , 307.84 ],
       shape=(1250,)),
 array([-6.2635, -6.2894, -6.0153, ..., 37.048 , 36.922 , 36.796 ],
       shape=(1250,)),
 array([-2.9075, -3.4321, -3.5567, ..., -9.2573, -8.6819, -7.9065],
       shape=(1250,)),
 array([14.042, 13.721, 13.5  , ..., 51.104, 52.083, 52.363], shape=(1250,)),
 array([203.76, 204.14, 204.52, ..., 438.53, 438.61, 439.29], shape=(1250,)),
 array([ 1.4463,  1.4995,  2.2526, ..., 62.534 , 61.787 , 61.24  ],
       shape=(1250,)),
 array([  -1.8313,   -1.8628,   -1.8942, ..., -273.32  , -273.36  ,
        -273.39  ], shape=(1250,)),
 array([   1.6299,    1.5572,    1.1845, ..., -253.73  , -253.8   ,
        -253.87  ], shape=(1250,)),
 array([ -19.391,  -16.57 ,  -13.348, ..., -120.18 , -118.36 , -118.33 ],
       shape=(1250,)),
 array([  16.672,   17.245,   17.119, ..., -168.11 , -171.64 , -171.76 ],
       shape=(1250,)),
 array([   9.6458,    9.4134,    9.4809, ..., -115.46  , -115.49  ,
        -116.02  ], shape=(1250,)),
 array([  -0.37491,   -0.2455 ,   -1.1161 , ..., -102.2    , -103.57   ,
        -106.04   ], shape=(1250,)),
 array([-2.6773e-03,  9.6623e-03,  2.2002e-02, ..., -1.0162e+02,
        -1.0160e+02, -1.0159e+02], shape=(1250,)),
 array([  24.829,   18.858,   16.187, ..., -236.1  , -236.07 , -233.44 ],
       shape=(1250,)),
 array([   4.4063,    4.1496,    1.9928, ..., -339.48  , -340.24  ,
        -340.49  ], shape=(1250,)),
 array([  5.6171,   4.2606,   2.304 , ..., -13.559 , -13.615 , -13.672 ],
       shape=(1250,)),
 array([  7.8149,   7.835 ,   7.855 , ..., -28.87  , -28.85  , -28.83  ],
       shape=(1250,)),
 array([   1.4896,    2.0781,    2.3665, ..., -504.11  , -504.83  ,
        -505.54  ], shape=(1250,)),
 array([  -5.3141,   -5.1841,   -4.7541, ..., -383.6   , -383.77  ,
        -384.94  ], shape=(1250,)),
 array([ -10.945,  -12.301,  -12.757, ..., -236.08 , -236.53 , -236.69 ],
       shape=(1250,)),
 array([ 15.319,  14.483,  12.947, ..., -79.511, -79.448, -79.384],
       shape=(1250,)),
 array([   2.2694 ,    0.98393,    0.99846, ..., -196.31   , -196.3    ,
        -197.78   ], shape=(1250,)),
 array([  17.928,   18.43 ,   19.132, ..., -160.19 , -161.19 , -161.29 ],
       shape=(1250,)),
 array([ 1.3608e-01,  5.3368e-01,  4.3128e-01, ..., -4.9535e+02,
        -4.9646e+02, -4.9556e+02], shape=(1250,)),
 array([  26.213,   23.595,   21.977, ..., -338.6  , -338.21 , -337.73 ],
       shape=(1250,)),
 array([  18.192,   17.308,   17.124, ..., -463.14 , -464.62 , -464.91 ],
       shape=(1250,)),
 array([ 12.918,  12.225,  12.832, ..., 729.56 , 730.67 , 731.58 ],
       shape=(1250,)),
 array([  35.216,   35.111,   36.006, ..., 1479.8  , 1480.8  , 1482.7  ],
       shape=(1250,)),
 array([   5.2456,    5.1452,    5.0449, ..., -159.61  , -160.41  ,
        -160.51  ], shape=(1250,)),
 array([ -2.0213,  -2.0016,  -1.1819, ..., -49.301 , -49.282 , -50.362 ],
       shape=(1250,)),
 array([ 7.0607e-01,  9.1748e-02,  7.7425e-02, ..., -1.3296e+02,
        -1.3237e+02, -1.3208e+02], shape=(1250,)),
 array([   6.4017,    5.5728,    5.0438, ..., -608.1   , -608.23  ,
        -607.86  ], shape=(1250,)),
 array([   1.7841,    2.414 ,    2.2439, ..., -246.26  , -246.73  ,
        -246.5   ], shape=(1250,)),
 array([ -35.604,  -35.072,  -35.14 , ..., -213.44 , -214.3  , -215.07 ],
       shape=(1250,)),
 array([ 5.8983,  5.5909,  6.0836, ..., 28.281 , 28.374 , 28.467 ],
       shape=(1250,)),
 array([  -6.1772,   -6.2417,   -6.3062, ..., -142.59  , -142.66  ,
        -142.02  ], shape=(1250,)),
 array([  12.282,   11.148,   10.914, ..., -255.85 , -255.38 , -255.42 ],
       shape=(1250,)),
 array([ 16.881,  14.58 ,  12.778, ..., 460.64 , 460.54 , 460.44 ],
       shape=(1250,)),
 array([ 17.681,  15.979,  15.977, ..., 396.67 , 396.87 , 397.77 ],
       shape=(1250,)),
 array([-3.5917, -4.5701, -4.6485, ..., 86.212 , 85.134 , 82.755 ],
       shape=(1250,)),
 array([-6.787 , -7.0954, -7.2039, ..., 94.698 , 94.59  , 95.281 ],
       shape=(1250,)),
 array([  7.099 ,   6.8468,   6.8946, ..., 128.44  , 128.49  , 128.54  ],
       shape=(1250,)),
 array([ -4.5241,  -4.2917,  -3.0593, ..., 225.89  , 225.92  , 225.35  ],
       shape=(1250,)),
 array([-79.881, -79.489, -77.797, ..., 610.26 , 611.75 , 611.14 ],
       shape=(1250,)),
 array([-11.255, -10.137,  -8.92 , ..., 146.91 , 146.93 , 146.95 ],
       shape=(1250,)),
 array([ -2.7799,  -2.7122,  -4.4444, ..., 222.37  , 222.24  , 222.31  ],
       shape=(1250,)),
 array([2.9432, 2.8269, 2.7105, ..., 5.2745, 5.1582, 4.1418], shape=(1250,)),
 array([   5.9472,    5.3101,    4.6729, ..., -549.68  , -549.62  ,
        -549.05  ], shape=(1250,)),
 array([22.58 , 21.799, 21.118, ..., 72.885, 72.804, 72.623], shape=(1250,)),
 array([ 3.9298,  4.0551,  4.1804, ..., 93.19  , 92.816 , 92.541 ],
       shape=(1250,)),
 array([ -7.6299,  -6.8408,  -6.2517, ..., -96.637 , -97.148 , -97.159 ],
       shape=(1250,)),
 array([ -5.2846,  -3.706 ,  -3.6274, ..., -18.293 , -17.415 , -17.336 ],
       shape=(1250,)),
 array([ 5.6673,  5.8607,  5.4541, ..., 88.897 , 89.49  , 89.784 ],
       shape=(1250,)),
 array([-3.3882, -3.4433, -4.4984, ..., 12.679 , 12.824 , 12.969 ],
       shape=(1250,)),
 array([  -8.834 ,   -9.8132,   -9.8925, ..., -123.01  , -122.39  ,
        -121.17  ], shape=(1250,)),
 array([  5.7616,   6.1054,   6.9492, ..., -34.427 , -33.083 , -32.039 ],
       shape=(1250,)),
 array([ -0.48363,  -0.35944,  -0.23526, ..., -94.623  , -94.499  ,
        -94.275  ], shape=(1250,)),
 array([ 7.239 ,  7.2891,  7.1392, ..., 51.47  , 52.02  , 52.07  ],
       shape=(1250,)),
 array([  49.252,   43.409,   42.766, ..., -163.58 , -163.92 , -165.56 ],
       shape=(1250,)),
 array([ 4.0587,  4.1   ,  4.1413, ..., -2.8214, -2.7801, -2.7388],
       shape=(1250,)),
 array([ 3.5155,  3.5874,  2.7594, ..., 64.908 , 64.98  , 65.052 ],
       shape=(1250,)),
 array([-6.6667, -6.6146, -6.0625, ..., 29.644 , 30.396 , 30.448 ],
       shape=(1250,)),
 array([   6.9796,    5.9583,    5.537 , ..., -447.01  , -447.93  ,
        -448.85  ], shape=(1250,)),
 array([35.991, 26.539, 24.488, ..., 80.408, 80.456, 80.705], shape=(1250,)),
 array([ 5.0805,  5.06  ,  5.0396, ..., 84.259 , 84.238 , 84.218 ],
       shape=(1250,)),
 array([ -3.0157,  -1.7208,  -3.0259, ..., -42.061 , -43.166 , -43.171 ],
       shape=(1250,)),
 array([-4.2057, -4.1722, -5.2386, ...,  7.6709,  7.0044,  7.038 ],
       shape=(1250,)),
 array([   8.9342,    7.2423,    7.1505, ..., -224.62  , -224.61  ,
        -224.7   ], shape=(1250,)),
 array([  -4.0735,   -4.2226,   -5.4716, ..., -317.96  , -319.21  ,
        -319.16  ], shape=(1250,)),
 array([-3.7453e-01, -6.1267e-01, -1.5081e-01, ..., -2.0873e+02,
        -2.0827e+02, -2.0751e+02], shape=(1250,)),
 array([ -5.1445,  -5.1245,  -5.1045, ..., -35.7   , -35.68  , -35.66  ],
       shape=(1250,)),
 array([  27.879,   27.001,   25.722, ..., -318.59 , -318.87 , -319.35 ],
       shape=(1250,)),
 array([   7.7562,    7.6687,    7.5812, ..., -159.47  , -159.36  ,
        -159.45  ], shape=(1250,)),
 array([ 8.2728,  9.1478,  9.2228, ..., 43.874 , 43.949 , 45.224 ],
       shape=(1250,)),
 array([-2.7153 , -1.8596 , -1.8039 , ...,  0.96123,  1.0169 ,  0.77266],
       shape=(1250,)),
 array([  3.4854,   4.2359,   4.1865, ..., -77.499 , -77.349 , -76.498 ],
       shape=(1250,)),
 array([-3.8635, -3.8763, -3.8892, ..., -3.4782, -3.891 , -4.1038],
       shape=(1250,)),
 array([ -29.016,  -29.178,  -28.141, ..., -357.75 , -358.21 , -358.88 ],
       shape=(1250,)),
 array([  7.5311,   4.7642,   2.5974, ..., -11.437 , -12.004 , -12.371 ],
       shape=(1250,)),
 array([  9.2356,   9.1338,   9.032 , ..., -39.148 , -39.25  , -39.352 ],
       shape=(1250,)),
 array([-2.8035, -2.8045, -1.2054, ..., 60.19  , 60.189 , 60.188 ],
       shape=(1250,)),
 array([-0.15673, -0.87694, -1.0971 , ..., 30.05   , 29.73   , 28.91   ],
       shape=(1250,)),
 array([ 2.6628,  2.2514,  2.2399, ..., 34.571 , 34.96  , 34.949 ],
       shape=(1250,)),
 array([-2.2052, -1.7186, -1.732 , ..., 48.576 , 48.562 , 48.549 ],
       shape=(1250,)),
 array([  1.315 ,  -1.1748,  -1.2646, ..., -27.863 , -28.753 , -29.842 ],
       shape=(1250,)),
 array([-0.13295, -0.93323, -1.0335 , ..., 11.516  , 12.116  , 11.815  ],
       shape=(1250,)),
 array([ 1.8382,  2.8186,  2.799 , ..., 40.701 , 41.281 , 42.462 ],
       shape=(1250,)),
 array([-9.2767, -9.2568, -7.7369, ..., 25.454 , 25.474 , 25.494 ],
       shape=(1250,)),
 array([ -20.261,  -20.565,  -21.269, ..., -430.65 , -430.95 , -431.65 ],
       shape=(1250,)),
 array([ -17.914,  -17.55 ,  -17.785, ..., -327.16 , -327.69 , -327.73 ],
       shape=(1250,)),
 array([   0.81535,    0.57443,    0.73352, ..., -126.9    , -126.94   ,
        -127.09   ], shape=(1250,)),
 array([ 0.78452,  0.87673,  0.96894, ..., 54.172  , 54.264  , 53.256  ],
       shape=(1250,)),
 array([ -2.4535,  -2.5444,  -2.9354, ..., -51.165 , -49.656 , -49.246 ],
       shape=(1250,)),
 array([   6.0776,    5.9599,    5.3421, ..., -120.14  , -119.46  ,
        -120.28  ], shape=(1250,)),
 array([   3.6359,    3.6058,    3.4758, ..., -133.7   , -133.73  ,
        -133.16  ], shape=(1250,)),
 array([-4.8507, -4.4728, -3.3948, ..., 65.553 , 65.631 , 65.708 ],
       shape=(1250,)),
 array([-3.7119 , -2.5544 , -0.79694, ...,  3.7457 ,  4.6032 ,  5.3607 ],
       shape=(1250,)),
 array([  6.2889,   6.2537,   6.2186, ..., -57.43  , -57.665 , -57.7   ],
       shape=(1250,)),
 array([   8.8705,    8.8138,    8.5572, ..., -133.8   , -133.96  ,
        -134.12  ], shape=(1250,)),
 array([  -1.9321,   -1.5574,   -3.1827, ..., -237.36  , -237.59  ,
        -238.71  ], shape=(1250,)),
 array([   0.31524,    0.23508,   -0.54508, ..., -119.94   , -120.02   ,
        -120.7    ], shape=(1250,)),
 array([   9.3785,    9.3021,    9.2257, ..., -122.8   , -122.98  ,
        -123.06  ], shape=(1250,)),
 array([57.864, 53.548, 48.732, ..., 57.626, 57.71 , 57.594], shape=(1250,)),
 array([   2.5922,    2.5565,    2.5208, ..., -107.81  , -107.84  ,
        -107.88  ], shape=(1250,)),
 array([ -1.6282,  -1.9485,  -1.9689, ..., -27.211 , -28.432 , -28.452 ],
       shape=(1250,)),
 array([ -1.1529,  -1.137 ,  -1.1211, ..., -14.568 , -15.853 , -15.837 ],
       shape=(1250,)),
 array([-1.0655 , -1.101  ,  0.56338, ..., 13.862  , 13.626  , 13.591  ],
       shape=(1250,)),
 array([ -7.3727,  -7.8711,  -7.8695, ..., -29.111 , -29.109 , -28.408 ],
       shape=(1250,)),
 array([-7.1757, -7.0784, -9.7812, ..., 79.048 , 79.146 , 77.343 ],
       shape=(1250,)),
 array([13.274 , 13.294 , 12.514 , ...,  7.5619,  7.5823,  6.0027],
       shape=(1250,)),
 array([ 2.2621e+00, -2.4172e-02, -1.0441e-02, ...,  2.9485e+01,
         2.9698e+01,  2.9712e+01], shape=(1250,)),
 array([  0.88439,   0.88089,   1.0774 , ..., -10.774  , -10.778  ,
        -10.781  ], shape=(1250,)),
 array([  0.73129,   0.72268,   0.71407, ..., -10.007  ,  -9.8155 ,
        -10.024  ], shape=(1250,)),
 array([ 0.74085,  0.80603,  0.87121, ..., 48.919  , 48.984  , 48.549  ],
       shape=(1250,)),
 array([-10.746, -10.776, -10.805, ..., -35.313, -35.342, -35.372],
       shape=(1250,)),
 array([ -7.2231,  -7.247 ,  -7.271 , ..., -41.588 , -41.612 , -41.636 ],
       shape=(1250,)),
 array([ 0.462 ,  1.0918,  1.6216, ..., 34.514 , 33.443 , 33.473 ],
       shape=(1250,)),
 array([-0.26685, -0.27277, -1.4787 , ...,  9.2538 ,  9.2479 ,  8.842  ],
       shape=(1250,)),
 array([   8.7502,    9.123 ,    8.8958, ..., -147.9   , -143.73  ,
        -143.06  ], shape=(1250,)),
 array([ -8.8325,  -8.3889,  -7.9453, ..., 232.65  , 233.09  , 233.54  ],
       shape=(1250,)),
 array([  5.1354,   5.2868,   5.4382, ..., 150.12  , 149.17  , 150.42  ],
       shape=(1250,)),
 array([1.3831e-01, 4.0987e-01, 3.3814e+00, ..., 3.6487e+02, 3.6514e+02,
        3.6541e+02], shape=(1250,)),
 array([  3.1689,   3.1895,   3.2102, ..., 135.41  , 135.43  , 135.45  ],
       shape=(1250,)),
 array([  17.067,   16.609,   16.151, ..., -404.46 , -406.32 , -406.78 ],
       shape=(1250,)),
 array([ 22.079,  22.222,  22.364, ..., 125.95 , 126.09 , 126.24 ],
       shape=(1250,)),
 array([ 22.807,  21.332,  21.357, ..., -52.55 , -46.225, -46.2  ],
       shape=(1250,)),
 array([ -16.149,  -16.014,  -15.878, ..., -180.54 , -180.41 , -179.97 ],
       shape=(1250,)),
 array([-1.1797e+00,  1.2106e+00,  7.8245e-04, ...,  2.6353e+02,
         2.6372e+02,  2.6391e+02], shape=(1250,)),
 array([ -0.47764,  -0.82392,  -0.9702 , ..., -75.586  , -75.732  ,
        -75.478  ], shape=(1250,)),
 array([ 8.6933,  5.4285,  5.7638, ..., 59.398 , 64.534 , 64.869 ],
       shape=(1250,)),
 array([  2.9555,   1.6478,   1.9402, ..., -64.019 , -63.727 , -64.034 ],
       shape=(1250,)),
 array([-3.9952, -3.9272, -3.8593, ..., 79.161 , 77.529 , 77.597 ],
       shape=(1250,)),
 array([   4.1585 ,    0.71542,    0.6723 , ..., -125.12   , -125.16   ,
        -125.21   ], shape=(1250,)),
 array([-3.6277e-02, -4.4774e+00, -4.5186e+00, ..., -4.9468e+01,
        -4.9509e+01, -5.2150e+01], shape=(1250,)),
 array([  10.709,   13.442,   10.575, ..., -131.76 , -134.42 , -132.29 ],
       shape=(1250,)),
 array([  -3.922 ,   -3.9619,   -7.1018, ..., -253.95  , -253.99  ,
        -254.03  ], shape=(1250,)),
 array([ 10.119,  10.119,  10.119, ..., -37.636, -32.937, -32.837],
       shape=(1250,)),
 array([ -9.4125,  -9.1475,  -8.8825, ..., -48.309 , -48.044 , -47.779 ],
       shape=(1250,)),
 array([ 0.075866,  0.026768, -0.022329, ..., 15.951   , 15.902   ,
        21.553   ], shape=(1250,)),
 array([ -7.2818, -11.559 , -11.336 , ...,  87.354 ,  87.577 ,  86.7   ],
       shape=(1250,)),
 array([  -0.76797,    2.1501 ,   -0.53188, ..., -112.96   , -112.94   ,
        -117.12   ], shape=(1250,)),
 array([-63.195, -60.086, -55.677, ..., -29.888, -29.479, -29.07 ],
       shape=(1250,)),
 array([-32.98 , -32.559, -32.137, ...,  72.96 ,  73.381,  73.803],
       shape=(1250,)),
 array([ 10.458 ,   7.1487,   7.2393, ..., -87.158 , -91.367 , -91.276 ],
       shape=(1250,)),
 array([   1.1909,    5.8063,    5.7218, ..., -101.39  ,  -97.876 ,
         -97.961 ], shape=(1250,)),
 array([ 0.5851,  3.5544,  1.1236, ..., 96.537 , 96.506 , 96.775 ],
       shape=(1250,)),
 array([-5.7402e-02, -1.1438e+00, -1.1302e+00, ..., -9.8592e+01,
        -9.8579e+01, -1.0366e+02], shape=(1250,)),
 array([ -2.7153,  -4.7868,  -4.4582, ..., 209.52  , 209.85  , 210.18  ],
       shape=(1250,)),
 array([ 1.9929,  2.2717,  2.5505, ..., 90.078 , 90.356 , 88.235 ],
       shape=(1250,)),
 array([   6.2307,    6.758 ,    6.6854, ..., -157.21  , -161.18  ,
        -157.35  ], shape=(1250,)),
 array([   6.4046,    8.9997,    5.9949, ..., -118.45  , -118.66  ,
        -119.46  ], shape=(1250,)),
 array([ 8.0057,  8.1024,  8.1991, ..., 59.07  , 57.767 , 57.863 ],
       shape=(1250,)),
 array([ -8.0861,  -7.9097,  -7.7333, ..., -28.58  , -28.404 , -30.727 ],
       shape=(1250,)),
 array([  -9.0064,   -6.1705,   -8.1346, ..., -221.05  , -218.21  ,
        -218.38  ], shape=(1250,)),
 array([   6.6483,    6.4744,    7.7004, ..., -244.83  , -245.01  ,
        -245.18  ], shape=(1250,)),
 array([  -2.4733,   -2.6044,   -2.7355, ..., -249.53  , -249.66  ,
        -249.79  ], shape=(1250,)),
 array([  26.089,   25.901,   25.714, ..., -370.77 , -372.36 , -372.55 ],
       shape=(1250,)),
 array([   7.726 ,    8.3085,    8.1911, ..., -217.56  , -217.68  ,
        -217.8   ], shape=(1250,)),
 array([ -5.6052,  -5.489 ,  -5.3728, ..., 279.28  , 277.4   , 279.51  ],
       shape=(1250,)),
 array([  0.55548,   1.0635 ,   1.5715 , ..., 496.64   , 497.65   ,
        497.96   ], shape=(1250,)),
 array([-31.673, -31.675, -27.076, ..., -56.833, -53.434, -53.436],
       shape=(1250,)),
 array([-1.1457e+00,  3.8899e-03,  2.5353e-01, ...,  3.4895e+02,
         3.4920e+02,  3.4945e+02], shape=(1250,)),
 array([ -2.174  ,  -2.0973 ,  -0.52065, ..., 262.13   , 262.2    ,
        263.38   ], shape=(1250,)),
 array([ -4.0226,  -5.5657,  -5.4088, ..., 197.03  , 197.19  , 197.34  ],
       shape=(1250,)),
 array([  1.3515,   1.3281,   1.3047, ..., 183.72  , 183.4   , 183.47  ],
       shape=(1250,)),
 array([ 8.2589,  8.1247,  7.9904, ..., 34.382 , 33.447 , 33.313 ],
       shape=(1250,)),
 array([ -3.5303,  -5.0415,  -5.2527, ..., -30.073 , -30.284 , -30.496 ],
       shape=(1250,)),
 array([ 5.8611,  5.7251,  5.589 , ..., 39.706 , 39.57  , 39.434 ],
       shape=(1250,)),
 array([ -18.16 ,  -18.121,  -18.082, ..., -115.99 , -115.95 , -115.91 ],
       shape=(1250,)),
 array([  13.727 ,    9.3395,   13.753 , ..., -135.58  , -135.57  ,
        -135.55  ], shape=(1250,)),
 array([ 1.4314e+00,  1.3928e+00,  1.5424e-01, ..., -2.0510e+02,
        -2.0603e+02, -2.0607e+02], shape=(1250,)),
 array([ -10.179,  -10.289,  -10.4  , ..., -271.67 , -267.68 , -269.99 ],
       shape=(1250,)),
 array([  -9.3313,   -9.3955,   -9.4596, ..., -270.69  , -270.76  ,
        -274.82  ], shape=(1250,)),
 array([ 1.3747e-01,  1.2574e-01,  1.1401e-01, ..., -1.9179e+02,
        -1.8900e+02, -1.9192e+02], shape=(1250,)),
 array([  -1.8228,   -1.7442,   -1.6656, ..., -134.65  , -134.48  ,
        -134.2   ], shape=(1250,)),
 array([  -3.0968,    1.3246,    1.446 , ..., -112.46  , -110.14  ,
        -110.02  ], shape=(1250,)),
 array([   1.062  ,    0.95326,    0.84451, ..., -297.15   , -297.26   ,
        -297.37   ], shape=(1250,)),
 array([  12.093,   10.357,   10.322, ..., -204.94 , -204.98 , -208.31 ],
       shape=(1250,)),
 array([  0.51567,   0.48928,   0.46289, ..., -29.394  , -30.22   ,
        -30.247  ], shape=(1250,)),
 array([ -1.5169,  -1.5858,  -1.6546, ..., -85.31  , -82.679 , -85.448 ],
       shape=(1250,)),
 array([ -5.7678,  -5.7742,  -5.7807, ..., -13.459 , -15.266 , -15.272 ],
       shape=(1250,)),
 array([0.55996, 0.60051, 0.64107, ..., 2.4335 , 2.474  , 1.9146 ],
       shape=(1250,)),
 array([  6.2043,   6.2526,   6.301 , ..., -19.386 , -20.137 , -20.089 ],
       shape=(1250,)),
 array([-10.057 ,  -8.9329,  -8.9083, ..., -13.638 , -16.513 , -16.489 ],
       shape=(1250,)),
 array([  -7.3733,   -8.2036,   -8.2338, ..., -110.04  , -112.77  ,
        -108.2   ], shape=(1250,)),
 array([  -5.1884,   -5.2895,   -5.3906, ..., -139.72  , -140.32  ,
        -139.92  ], shape=(1250,)),
 array([ -1.7743,  -1.8028,  -3.9313, ..., -67.549 , -67.577 , -68.606 ],
       shape=(1250,)),
 array([  4.8923,   4.8656,   4.8388, ..., -95.989 , -96.815 , -96.842 ],
       shape=(1250,)),
 array([  11.407,   11.285,   11.163, ..., -236.48 , -236.6  , -236.72 ],
       shape=(1250,)),
 array([  -1.7064 ,   -1.7938 ,   -0.58122, ..., -199.7    , -200.98   ,
        -199.87   ], shape=(1250,)),
 array([ -15.198,  -15.272,  -15.345, ..., -171.66 , -174.44 , -174.51 ],
       shape=(1250,)),
 array([ -10.529 ,  -10.621 ,   -5.3136, ..., -203.34  , -203.43  ,
        -199.82  ], shape=(1250,)),
 array([  -6.6424,   -6.6733,   -6.7041, ..., -243.8   , -243.83  ,
        -243.06  ], shape=(1250,)),
 array([  -7.3327,   -7.3164,   -7.3   , ..., -136.12  , -136.1   ,
        -136.08  ], shape=(1250,)),
 array([  -2.2133,   -2.2784,   -2.8434, ..., -253.84  , -253.91  ,
        -254.27  ], shape=(1250,)),
 array([  17.172,   16.865,   16.558, ..., -431.06 , -431.37 , -431.68 ],
       shape=(1250,)),
 array([  16.228,   18.505,   18.382, ..., -338.33 , -338.46 , -338.58 ],
       shape=(1250,)),
 array([  -2.307 ,   -2.5283,   -2.7495, ..., -382.26  , -383.88  ,
        -382.7   ], shape=(1250,)),
 array([  -6.2758,   -6.4058,   -6.8359, ..., -125.1   , -125.23  ,
        -125.36  ], shape=(1250,)),
 array([-0.03308, -3.4062 , -3.3794 , ..., 22.763  , 22.79   , 22.817  ],
       shape=(1250,)),

In [44]:
y_test = []
for linha in dataset_exemplo_teste.iloc[:, 0].values:
    y_test.append(linha)
y_test

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12)]

Normalizando os dados

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)