# Experimentos

## Importando requisitos

In [1]:
import pandas
import os
import numpy

## Abrindo a planilha

In [2]:
planilha = pandas.read_csv('../Dataset/DataSummary.csv')
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall
...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Filtrando na planilha os datasets selecionados

In [3]:
planilha = planilha[planilha['ID'].between(97, 128)]
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
96,97,EOG,EOGVerticalSignal,362,362,12,1250,0.5580,0.5249 (2),0.5525,0.9144,E. Keogh & H. A. Dau
97,98,Spectro,EthanolLevel,504,500,4,1751,0.7260,0.7180 (1),0.7240,0.7480,A. Bagnall
98,99,Sensor,FreezerRegularTrain,150,2850,2,301,0.1951,0.0930 (1),0.1011,0.5000,REFIT project
99,100,Sensor,FreezerSmallTrain,28,2850,2,301,0.3242,0.3242 (0),0.2411,0.5000,REFIT project
100,101,HRM,Fungi,18,186,18,201,0.1774,0.1774 (0),0.1613,0.8978,W. Fonzi
101,102,Trajectory,GestureMidAirD1,208,130,26,Vary,0.4231,0.3615 (5),0.4308,0.9615,H. A. Dau
102,103,Trajectory,GestureMidAirD2,208,130,26,Vary,0.5077,0.4000 (6),0.3923,0.9615,H. A. Dau
103,104,Trajectory,GestureMidAirD3,208,130,26,Vary,0.6538,0.6231 (1),0.6769,0.9615,H. A. Dau
104,105,Sensor,GesturePebbleZ1,132,172,6,Vary,0.2674,0.1744 (2),0.2093,0.8140,I. Maglogiannis
105,106,Sensor,GesturePebbleZ2,146,158,6,Vary,0.3291,0.2215 (6),0.3291,0.8101,I. Maglogiannis
106,107,Motion,GunPointAgeSpan,135,316,2,150,0.1013,0.0348 (3),0.0823,0.4937,A. Ratanamahatana & E. Keogh
107,108,Motion,GunPointMaleVersusFemale,135,316,2,150,0.0253,0.0253 (0),0.0032,0.4747,A. Ratanamahatana & E. Keogh
108,109,Motion,GunPointOldVersusYoung,136,315,2,150,0.0476,0.0349 (4),0.1619,0.4762,A. Ratanamahatana & E. Keogh
109,110,Device,HouseTwenty,40,119,2,2000,0.3361,0.0588 (33),0.0756,0.4202,E. Keogh & S. Gharghabi
110,111,EPG,InsectEPGRegularTrain,62,249,3,601,0.3213,0.1727 (11),0.1285,0.5261,E. Keogh & S. Gharghabi
111,112,EPG,InsectEPGSmallTrain,17,249,3,601,0.3373,0.3052 (1),0.2651,0.5261,E. Keogh & S. Gharghabi
112,113,Traffic,MelbournePedestrian,1194,2439,10,24,0.1525,0.1845 (1),0.2091,0.8995,H.A. Dau
113,114,Image,MixedShapesRegularTrain,500,2425,5,1024,0.1027,0.0911 (4),0.1584,0.7303,E. Keogh
114,115,Image,MixedShapesSmallTrain,100,2425,5,1024,0.1645,0.1674 (7),0.2202,0.7303,E. Keogh
115,116,Sensor,PickupGestureWiimoteZ,50,50,10,Vary,0.4400,0.3400 (17),0.3400,0.9000,J. Guna
116,117,Hemodynamics,PigAirwayPressure,104,208,52,2000,0.9423,0.9038 (1),0.8942,0.9808,M. Guillame-Bert
117,118,Hemodynamics,PigArtPressure,104,208,52,2000,0.8750,0.8029 (1),0.7548,0.9808,M. Guillame-Bert
118,119,Hemodynamics,PigCVP,104,208,52,2000,0.9183,0.8413 (11),0.8462,0.9808,M. Guillame-Bert
119,120,Device,PLAID,537,537,11,Vary,0.4767,0.1657 (12),0.1639,0.8380,P. Schafer
120,121,Power,PowerCons,180,180,2,144,0.0667,0.0778 (3),0.1222,0.5000,"EDF R&D, France"
121,122,Spectrum,Rock,20,50,4,2844,0.1600,0.1600 (0),0.4000,0.5800,Y. Zhu
122,123,Spectrum,SemgHandGenderCh2,300,600,2,1500,0.2383,0.1550 (1),0.1983,0.3500,C.-C. M. Yeh
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Realizando experimentos no dataset da primeira linha da tabela

Obtendo o caminho do dataset de exemplo

In [4]:
dataset_exemplo = planilha.iloc[0]['Name']
dataset_exemplo

'EOGVerticalSignal'

In [5]:
dataset_dirname = os.path.join('../Dataset/UCRArchive_2018', dataset_exemplo)
dataset_dirname

'../Dataset/UCRArchive_2018/EOGVerticalSignal'

In [6]:
caminho_arquivo_treino = os.path.join(dataset_dirname, '{}_TRAIN.tsv'.format(dataset_exemplo))
caminho_arquivo_treino

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TRAIN.tsv'

In [7]:
caminho_arquivo_teste = os.path.join(dataset_dirname, '{}_TEST.tsv'.format((dataset_exemplo)))
caminho_arquivo_teste

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TEST.tsv'

Abrindo datasets

In [8]:
dataset_exemplo_treino = pandas.read_csv(caminho_arquivo_treino, sep='\t', header=None)
dataset_exemplo_treino

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,-5.70320,-5.89550,-5.88780,-6.08000,-6.17230,-6.26460,-6.2568,-6.1491,-6.4414,...,-113.3100,-113.4100,-113.50000,-114.390000,-114.4800,-113.77000,-113.0700,-113.1600,-112.8500,-112.9400
1,1,-2.18020,-2.30860,-2.33690,-2.36520,-2.39360,-2.02190,-2.0502,-2.0786,-2.5069,...,108.3900,108.5600,108.53000,108.500000,108.4700,108.45000,108.4200,108.3900,108.1600,108.1300
2,1,6.70950,6.52680,6.34420,6.16160,5.97900,5.79640,5.6137,4.5311,2.7485,...,-34.9360,-35.1190,-35.30100,-35.484000,-35.6660,-34.94900,-35.1320,-35.3140,-34.5970,-34.7800
3,1,-0.91251,-0.72238,-0.53226,-0.74213,-0.95201,-1.16190,-1.5718,-1.7816,-1.1915,...,-173.8600,-174.0700,-173.68000,-173.890000,-174.7000,-174.71000,-174.9200,-175.1300,-174.7400,-174.3500
4,1,-5.44400,-5.32610,-4.10820,-3.69020,-3.57230,-3.45440,-3.0364,-2.6185,-2.5006,...,2.0864,1.8044,1.92230,2.040200,2.1582,2.27610,2.3940,2.5119,2.6299,2.7478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,-4.32250,-2.52830,-2.83410,-2.83980,-2.84560,-2.85130,-4.3571,-4.3629,-4.3686,...,-2.1725,-1.3783,-0.08404,-0.089806,1.5044,-0.10134,-1.1071,-1.1129,-1.3186,-1.3244
358,12,-5.91600,-5.90050,-6.68500,-7.76950,-7.75400,-7.73850,-6.6230,-6.6075,-6.5920,...,32.0100,28.3260,25.44100,27.857000,32.0720,32.08800,31.9030,27.9190,27.9340,27.9500
359,12,2.66670,2.60940,2.55220,4.59490,1.63760,0.38033,2.4231,4.0658,2.3085,...,-42.8540,-42.9110,-42.96900,-43.026000,-44.3830,-45.84000,-44.4980,-44.5550,-44.6120,-47.1690
360,12,-1.22680,-1.24790,1.63100,1.50990,1.38880,3.16770,3.0465,2.9254,3.4043,...,-97.5090,-94.3310,-97.75200,-94.573000,-94.6940,-94.81500,-94.9360,-98.0570,-102.5800,-102.7000
361,12,-11.76000,-9.95780,-12.15500,-12.25300,-10.25000,-12.74800,-10.4450,-12.1430,-11.8400,...,-100.6800,-100.7800,-100.07000,-100.170000,-101.0700,-100.37000,-100.4600,-101.3600,-101.4600,-100.7600

In [9]:
dataset_exemplo_teste = pandas.read_csv(caminho_arquivo_teste, sep='\t', header=None)
dataset_exemplo_teste

,0,1,2,3,4,5,6,7,8,9,...,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250
0,1,2.67520,2.68930,3.2034,4.01750,3.93150,3.94560,3.55970,3.87380,3.48790,...,-394.470,-392.450,-391.240,-390.830,-390.710,-390.900,-390.980,-390.870,-390.850,-390.740
1,1,6.84840,6.17140,5.6944,5.31730,5.14030,4.96330,4.18620,3.60920,2.73220,...,-145.670,-144.850,-144.220,-143.900,-143.680,-143.860,-143.530,-144.210,-144.790,-144.960
2,1,-4.91380,-4.87180,-4.8298,-4.98790,-5.14590,-4.50390,-4.66190,-3.72000,-3.57800,...,-169.270,-169.430,-169.590,-169.140,-169.100,-169.260,-169.420,-169.980,-170.730,-170.890
3,1,18.27800,18.29000,18.3020,18.31400,18.32600,19.13800,19.15000,19.86200,19.17400,...,308.330,307.840,308.350,307.670,307.380,308.290,308.300,308.310,307.830,307.840
4,1,-6.26350,-6.28940,-6.0153,-5.34120,-5.46710,-6.09300,-6.71890,-6.34470,-6.47060,...,39.229,38.503,38.077,37.551,37.425,36.499,36.374,37.048,36.922,36.796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,12,2.02960,1.62900,1.2284,0.92786,0.72729,0.42672,0.42615,0.12558,0.12501,...,-12.375,-14.576,-14.576,-12.577,-12.577,-11.278,-11.279,-12.579,-11.280,-12.580
358,12,1.39790,1.59650,1.6951,0.89369,1.09230,1.29090,0.28948,0.08808,0.28668,...,132.660,132.460,132.660,132.850,133.450,133.950,133.850,134.050,133.850,134.350
359,12,1.90450,1.74240,1.8803,3.41830,2.15620,1.99420,2.13210,3.97010,4.10800,...,93.154,92.992,92.630,92.068,90.606,89.744,89.282,89.020,88.758,88.896
360,12,17.80400,16.97900,16.5540,16.02900,15.70400,15.07800,14.75300,13.22800,11.50300,...,-419.660,-419.990,-420.310,-420.040,-420.060,-420.390,-420.510,-420.840,-421.160,-421.490
361,12,-0.10837,0.44276,1.4939,2.34500,2.29610,2.94730,2.89840,2.84950,2.10070,...,-103.210,-103.860,-103.910,-103.950,-104.300,-104.050,-104.100,-104.450,-104.500,-104.950

### Formatando Dataset

In [10]:
def formatar_dataset(df: pandas.DataFrame) -> pandas.DataFrame:
    """
    Realiza a formatação do dataset.
    :param df: Dataset a ser formatado.
    :return: Dataset formatado.
    """
    classe = df.iloc[:, 0]
    series = df.iloc[:, 1:]

    df_novo = pandas.DataFrame({
        'classe': classe,
        'SérieTemporal': list(series.to_numpy())
    })

    return df_novo

In [11]:
dataset_exemplo_treino = formatar_dataset(dataset_exemplo_treino)
dataset_exemplo_treino

     classe                                      SérieTemporal
0         1  [-5.7032, -5.8955, -5.8878, -6.08, -6.1723, -6...
1         1  [-2.1802, -2.3086, -2.3369, -2.3652, -2.3936, ...
2         1  [6.7095, 6.5268, 6.3442, 6.1616, 5.979, 5.7964...
3         1  [-0.91251, -0.72238, -0.53226, -0.74213, -0.95...
4         1  [-5.444, -5.3261, -4.1082, -3.6902, -3.5723, -...
..      ...                                                ...
357      12  [-4.3225, -2.5283, -2.8341, -2.8398, -2.8456, ...
358      12  [-5.916, -5.9005, -6.685, -7.7695, -7.754, -7....
359      12  [2.6667, 2.6094, 2.5522, 4.5949, 1.6376, 0.380...
360      12  [-1.2268, -1.2479, 1.631, 1.5099, 1.3888, 3.16...
361      12  [-11.76, -9.9578, -12.155, -12.253, -10.25, -1...

[362 rows x 2 columns]

In [12]:
dataset_exemplo_teste = formatar_dataset(dataset_exemplo_teste)
dataset_exemplo_teste

     classe                                      SérieTemporal
0         1  [2.6752, 2.6893, 3.2034, 4.0175, 3.9315, 3.945...
1         1  [6.8484, 6.1714, 5.6944, 5.3173, 5.1403, 4.963...
2         1  [-4.9138, -4.8718, -4.8298, -4.9879, -5.1459, ...
3         1  [18.278, 18.29, 18.302, 18.314, 18.326, 19.138...
4         1  [-6.2635, -6.2894, -6.0153, -5.3412, -5.4671, ...
..      ...                                                ...
357      12  [2.0296, 1.629, 1.2284, 0.92786, 0.72729, 0.42...
358      12  [1.3979, 1.5965, 1.6951, 0.89369, 1.0923, 1.29...
359      12  [1.9045, 1.7424, 1.8803, 3.4183, 2.1562, 1.994...
360      12  [17.804, 16.979, 16.554, 16.029, 15.704, 15.07...
361      12  [-0.10837, 0.44276, 1.4939, 2.345, 2.2961, 2.9...

[362 rows x 2 columns]

### Aplicando algoritmos nos datasets

In [13]:
from app.model.DynamicTimeWarping import DynamicTimeWarping
from app.model.DerivativeDynamicTimeWarping import DerivativeDynamicTimeWarping
from app.model.LongestCommonSubsequence import LongestCommonSubsequence
from app.model.SoftDynamicTimeWarping import SoftDynamicTimeWarping

def aplicar_algoritmos_series_temporais(dataset: pandas.DataFrame, indice_serie_referencia: int = 0) -> pandas.DataFrame:
    """
    Aplica algoritmos às séries temporais.
    :param dataset: Dataset.
    :param indice_serie_referencia: Índice da série temporal de referência.
    :return: Dataset com as distâncias das séries temporais.
    """
    # Instanciando algoritmos
    dtw = DynamicTimeWarping()
    ddtw = DerivativeDynamicTimeWarping()
    lcs = LongestCommonSubsequence()
    soft_dtw = SoftDynamicTimeWarping()

    # Definindo série de referência
    serie_referencia = dataset.iloc[indice_serie_referencia]["SérieTemporal"]

    # Executando algoritmos e adicionando ao Dataset
    print('Executando Dynamic Time Warping')
    dataset_exemplo_treino['dtw'] = dataset_exemplo_treino['SérieTemporal'].apply(
        lambda s: dtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Dynamic Time Warping')

    print('Executando o Derivative Dynamic Time Warping')
    dataset_exemplo_treino['ddtw'] = dataset_exemplo_treino['SérieTemporal'].apply(
        lambda s: ddtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Derivative Dynamic Time Warping')

    print('Executando o Longest Common Subsequence')
    dataset_exemplo_treino['lcs'] = dataset_exemplo_treino['SérieTemporal'].apply(
        lambda s: lcs.lcs(s, serie_referencia)
    )
    print('Finalizado o Longest Common Subsequence')

    print('Executando o Soft Dynamic Time Warping')
    dataset_exemplo_treino['soft-dtw'] = dataset_exemplo_treino['SérieTemporal'].apply(
        lambda s: soft_dtw.obter_distancia(s, serie_referencia)
    )
    print('Finalizado o Soft Dynamic Time Warping')

    return dataset

In [14]:
dataset_exemplo_treino = aplicar_algoritmos_series_temporais(dataset_exemplo_treino)

In [57]:
dataset_exemplo_teste = aplicar_algoritmos_series_temporais(dataset_exemplo_teste)

KeyError: 'SérieTemporal'

### Criando conjuntos de teste e treino

In [49]:
dataset_exemplo_treino

     classe           dtw         ddtw   lcs      soft-dtw
0         1      0.000000     0.000000  1250 -1.625967e+03
1         1  94123.211165   417.935442  1249  1.490889e+07
2         1  30054.421325   420.707073  1249  1.901112e+06
3         1  14798.394310   481.370766  1249  5.967205e+05
4         1  65684.048861   471.058642  1249  5.371476e+06
..      ...           ...          ...   ...           ...
357      12  50358.440768  1368.307540  1249  4.388884e+06
358      12  66425.290402  1557.679812  1249  7.836528e+06
359      12  27812.949282  1445.712285  1249  1.841132e+06
360      12   9598.673229  1463.615157  1249  5.416825e+05
361      12  10612.047232  1385.728561  1249  4.874493e+05

[362 rows x 5 columns]

In [48]:
dataset_exemplo_teste

     classe
0         1
1         1
2         1
3         1
4         1
..      ...
357      12
358      12
359      12
360      12
361      12

[362 rows x 1 columns]

Obtendo conjuntos de treino e teste: x e y

In [50]:
def separar_x_y(dataset: pandas.DataFrame) -> tuple[list, list]:
    """
    Separa o conjunto de treino do conjunto de teste
    :param dataset: Dataset de entrada.
    :return: Tupla com os cunjuntos de treino e teste.
    """
    x = []
    for linha in dataset.iloc[:, 1:].values:
        x.append(linha)

    y = []
    for linha in dataset.iloc[:, 0].values:
        y.append(linha)

    return x, y

In [51]:
x_train, y_train = separar_x_y(dataset_exemplo_treino)

In [52]:
x_train

[array([    0.        ,     0.        ,  1250.        , -1625.96669436]),
 array([9.41232112e+04, 4.17935442e+02, 1.24900000e+03, 1.49088882e+07]),
 array([3.00544213e+04, 4.20707073e+02, 1.24900000e+03, 1.90111231e+06]),
 array([1.47983943e+04, 4.81370766e+02, 1.24900000e+03, 5.96720469e+05]),
 array([6.56840489e+04, 4.71058642e+02, 1.24900000e+03, 5.37147558e+06]),
 array([1.23007499e+05, 5.20173906e+02, 1.24900000e+03, 2.14923496e+07]),
 array([1.66111491e+05, 6.05359252e+02, 1.24900000e+03, 5.03355413e+07]),
 array([3.39844938e+05, 7.89290984e+02, 1.24900000e+03, 1.79937429e+08]),
 array([1.77183361e+04, 4.11772464e+02, 1.24900000e+03, 7.06811330e+05]),
 array([7.76364512e+04, 5.40979902e+02, 1.24900000e+03, 1.08588408e+07]),
 array([ 13073.7391311 ,    711.53500775,   1249.        , 522114.71723225]),
 array([5.27595234e+04, 7.39629932e+02, 1.24900000e+03, 5.09232828e+06]),
 array([4.37098840e+04, 8.33194536e+02, 1.24900000e+03, 3.32955704e+06]),
 array([ 11160.1290608,    723.5860963,   1249.       , 661797.8978005]),
 array([3.95636181e+04, 7.69482841e+02, 1.24900000e+03, 2.80392339e+06]),
 array([6.83938593e+04, 6.49314161e+02, 1.24900000e+03, 7.75900350e+06]),
 array([9.33639191e+04, 7.92470020e+02, 1.24900000e+03, 1.50953041e+07]),
 array([1.80925600e+04, 7.74501426e+02, 1.24900000e+03, 1.22019244e+06]),
 array([7.87607386e+04, 8.46478358e+02, 1.24900000e+03, 1.09202266e+07]),
 array([5.64279771e+04, 1.00013162e+03, 1.24900000e+03, 6.27226411e+06]),
 array([1.13605217e+05, 7.35816143e+02, 1.24900000e+03, 1.60548090e+07]),
 array([3.23120983e+04, 6.55612127e+02, 1.24900000e+03, 1.83187515e+06]),
 array([ 18647.3686188 ,    962.01751685,   1249.        , 883116.45231483]),
 array([ 14046.170281  ,    871.48885925,   1249.        , 730186.15531003]),
 array([2.87555726e+04, 7.36063026e+02, 1.24900000e+03, 1.28815868e+06]),
 array([6.04574884e+04, 6.88782319e+02, 1.24900000e+03, 6.10063918e+06]),
 array([4.92721854e+04, 7.67519955e+02, 1.24900000e+03, 4.05488865e+06]),
 array([1.41196829e+04, 8.37442142e+02, 1.24900000e+03, 9.60900106e+05]),
 array([3.18247546e+04, 7.81243950e+02, 1.24900000e+03, 1.64826792e+06]),
 array([3.65664324e+04, 1.01632180e+03, 1.24900000e+03, 2.48094037e+06]),
 array([3.23404489e+04, 6.71062105e+02, 1.24900000e+03, 1.65193078e+06]),
 array([2.76655834e+04, 5.82454185e+02, 1.24900000e+03, 1.00699610e+06]),
 array([ 10952.7172867 ,    775.1131971 ,   1249.        , 516897.78600593]),
 array([ 13808.433569  ,    907.5777985 ,   1249.        , 484364.20242439]),
 array([3.07780455e+04, 8.09694195e+02, 1.24900000e+03, 1.47828111e+06]),
 array([ 22329.2652796,    784.3745849,   1249.       , 729822.5337177]),
 array([4.15313777e+04, 6.96186199e+02, 1.24900000e+03, 2.98096028e+06]),
 array([3.79658102e+04, 8.78403708e+02, 1.24900000e+03, 2.50393379e+06]),
 array([  9202.838492  ,    925.95989675,   1249.        , 442912.69851757]),
 array([2.45838230e+04, 9.12326870e+02, 1.24900000e+03, 1.29359003e+06]),
 array([7.48481506e+04, 6.99088757e+02, 1.24900000e+03, 7.02516038e+06]),
 array([1.92738995e+05, 7.19691523e+02, 1.24900000e+03, 4.63157370e+07]),
 array([1.34469766e+05, 8.02384395e+02, 1.24900000e+03, 2.18451968e+07]),
 array([1.90209306e+05, 9.44547367e+02, 1.24900000e+03, 4.59386701e+07]),
 array([2.08256308e+04, 7.93019539e+02, 1.24900000e+03, 9.94710162e+05]),
 array([2.03995710e+05, 6.32243513e+02, 1.24900000e+03, 5.19286275e+07]),
 array([1.55785369e+05, 7.45536044e+02, 1.24900000e+03, 2.92476620e+07]),
 array([8.64307094e+04, 7.97507481e+02, 1.24900000e+03, 8.80177475e+06]),
 array([1.33233174e+05, 9.37230353e+02, 1.24900000e+03, 2.32984266e+07]),
 array([1.05289689e+05, 7.95609172e+02, 1.24900000e+03, 1.35500245e+07]),
 array([3.86761508e+04, 6.42339589e+02, 1.24900000e+03, 2.63236694e+06]),
 array([2.20240474e+04, 6.58283130e+02, 1.24900000e+03, 9.49106363e+05]),
 array([ 5298.375216  ,   566.35685225,  1249.        , 47322.53832777]),
 array([ 17700.18685649,    598.94599505,   1249.        , 493023.8982795 ]),
 array([ 13297.2960362 ,    670.8956583 ,   1249.        , 264261.14740332]),
 array([3.33566001e+04, 5.17416256e+02, 1.24900000e+03, 1.51161048e+06]),
 array([ 12477.62423   ,    599.495062  ,   1249.        , 158971.69120945]),
 array([ 8089.36771072,   627.88933361,  1249.        , 75295.49925035]),
 array([4.20098985e+04, 5.98639986e+02, 1.24900000e+03, 2.04307782e+06]),
 array([4.51657710e+04, 5.98963683e+02, 1.24900000e+03, 2.51678074e+06]),
 array([8.05396226e+04, 7.20877630e+02, 1.24900000e+03, 9.01617040e+06]),
 array([5.66269768e+04, 8.50053102e+02, 1.24900000e+03, 5.01451211e+06]),
 array([7.53597664e+04, 7.90462345e+02, 1.24900000e+03, 8.70831847e+06]),
 array([4.94745236e+04, 8.11066663e+02, 1.24900000e+03, 4.24979597e+06]),
 array([3.68755445e+04, 7.10572173e+02, 1.24900000e+03, 2.62307406e+06]),
 array([4.80683521e+04, 8.06289119e+02, 1.24900000e+03, 4.25413196e+06]),
 array([1.15518090e+05, 7.42228026e+02, 1.24900000e+03, 1.96594089e+07]),
 array([5.77496861e+04, 7.32965082e+02, 1.24900000e+03, 6.70814099e+06]),
 array([ 12301.452655  ,    771.0484515 ,   1249.        , 303693.22192234]),
 array([2.78300940e+04, 7.24465486e+02, 1.24900000e+03, 1.72351710e+06]),
 array([2.83898392e+04, 6.60007128e+02, 1.24900000e+03, 1.30945357e+06]),
 array([3.28940899e+04, 7.21942289e+02, 1.24900000e+03, 2.44783337e+06]),
 array([2.70536205e+04, 5.73902216e+02, 1.24900000e+03, 1.36115854e+06]),
 array([8.49042710e+04, 8.63046757e+02, 1.24900000e+03, 1.13402538e+07]),
 array([3.79516030e+04, 6.86867068e+02, 1.24900000e+03, 3.09405365e+06]),
 array([3.49817168e+05, 1.08838355e+03, 1.24900000e+03, 1.65384148e+08]),
 array([3.15171381e+04, 7.03066733e+02, 1.24900000e+03, 2.10116441e+06]),
 array([5.55357296e+04, 7.13348173e+02, 1.24900000e+03, 5.51343584e+06]),
 array([5.42480019e+04, 8.72824415e+02, 1.24900000e+03, 5.18113015e+06]),
 array([8.05624912e+04, 7.66666534e+02, 1.24900000e+03, 8.93310005e+06]),
 array([3.72763854e+04, 6.90676504e+02, 1.24900000e+03, 2.88212556e+06]),
 array([7.59108083e+04, 8.35528015e+02, 1.24900000e+03, 9.33881148e+06]),
 array([6.47319083e+04, 7.56298710e+02, 1.24900000e+03, 5.86109394e+06]),
 array([8.12428308e+04, 8.68828487e+02, 1.24900000e+03, 9.87466740e+06]),
 array([5.82765632e+04, 1.04631167e+03, 1.24900000e+03, 7.29232544e+06]),
 array([6.30794768e+04, 9.62457816e+02, 1.24900000e+03, 7.49854853e+06]),
 array([4.76317819e+04, 9.06578820e+02, 1.24900000e+03, 4.78993160e+06]),
 array([7.00924458e+04, 1.01514049e+03, 1.24900000e+03, 8.19068863e+06]),
 array([6.07446454e+04, 8.53589539e+02, 1.24900000e+03, 6.45942168e+06]),
 array([9.10060732e+04, 1.16877548e+03, 1.24900000e+03, 1.33742703e+07]),
 array([1.11276181e+05, 8.96537934e+02, 1.24900000e+03, 1.79284348e+07]),
 array([3.58449506e+04, 1.10202496e+03, 1.24900000e+03, 2.39622033e+06]),
 array([1.87603835e+04, 9.32965883e+02, 1.24900000e+03, 1.72432206e+06]),
 array([4.70573701e+04, 1.13782122e+03, 1.24900000e+03, 3.79865521e+06]),
 array([2.45919033e+04, 1.20305678e+03, 1.24900000e+03, 2.35462182e+06]),
 array([2.80800212e+04, 1.05608196e+03, 1.24900000e+03, 2.93866456e+06]),
 array([9.41205024e+04, 1.23635263e+03, 1.24900000e+03, 1.46938144e+07]),
 array([3.55906451e+04, 1.23909593e+03, 1.24900000e+03, 2.94353616e+06]),
 array([4.13033354e+04, 1.29261554e+03, 1.24900000e+03, 3.78268928e+06]),
 array([3.25003175e+04, 1.23560599e+03, 1.24900000e+03, 2.99487526e+06]),
 array([1.49599982e+05, 8.61406667e+02, 1.24900000e+03, 2.99261041e+07]),
 array([9.45850164e+04, 8.16166593e+02, 1.24900000e+03, 1.33302991e+07]),
 array([2.06854369e+04, 8.17949108e+02, 1.24900000e+03, 1.35385815e+06]),
 array([8.03780062e+04, 1.03809572e+03, 1.24900000e+03, 1.00839453e+07]),
 array([ 15948.153384  ,    820.61306425,   1249.        , 574942.45015156]),
 array([6.61130304e+04, 8.49062520e+02, 1.24900000e+03, 7.12284062e+06]),
 array([5.70155160e+04, 1.07062708e+03, 1.24900000e+03, 4.95202467e+06]),
 array([2.95007508e+04, 6.97907640e+02, 1.24900000e+03, 2.21331802e+06]),
 array([1.25010149e+05, 1.08436583e+03, 1.24900000e+03, 2.20951027e+07]),
 array([6.67457908e+04, 1.03132373e+03, 1.24900000e+03, 7.90929216e+06]),
 array([3.44104240e+04, 9.52192049e+02, 1.24900000e+03, 2.70010428e+06]),
 array([9.73735758e+04, 9.45338344e+02, 1.24900000e+03, 1.56108933e+07]),
 array([6.56753953e+04, 8.56112500e+02, 1.24900000e+03, 6.44872041e+06]),
 array([6.49988374e+04, 9.82067691e+02, 1.24900000e+03, 5.79674394e+06]),
 array([2.75374782e+04, 8.85226126e+02, 1.24900000e+03, 2.07476013e+06]),
 array([6.67099482e+04, 1.04120638e+03, 1.24900000e+03, 6.99497430e+06]),
 array([1.46012066e+04, 8.29422204e+02, 1.24900000e+03, 1.01315919e+06]),
 array([4.79949785e+04, 9.79178969e+02, 1.24900000e+03, 4.15997333e+06]),
 array([  24295.067905  ,    1064.303881  ,    1249.        ,
        1029596.99060989]),
 array([8.20135536e+04, 1.03131641e+03, 1.24900000e+03, 1.07478221e+07]),
 array([2.95130527e+04, 4.19890720e+02, 1.24900000e+03, 1.73845921e+06]),
 array([2.09012016e+04, 4.77424170e+02, 1.24900000e+03, 8.34355404e+05]),
 array([2.82525923e+04, 5.30809345e+02, 1.24900000e+03, 1.69108624e+06]),
 array([3.87217508e+04, 5.84443728e+02, 1.24900000e+03, 2.78406068e+06]),
 array([  9653.398075  ,    521.79605625,   1249.        , 175435.86473956]),
 array([2.05319989e+04, 5.43884593e+02, 1.24900000e+03, 9.25628431e+05]),
 array([ 13669.0704772 ,    504.1899924 ,   1249.        , 393930.34708776]),
 array([8.01195031e+04, 5.62240678e+02, 1.24900000e+03, 1.00501041e+07]),
 array([7.44478726e+04, 5.14762041e+02, 1.24900000e+03, 9.60790033e+06]),
 array([ 15792.6452254 ,    515.13536235,   1249.        , 512699.87868732]),
 array([ 15116.228319  ,    840.247436  ,   1249.        , 773672.99865831]),
 array([1.95000604e+04, 1.06231557e+03, 1.24900000e+03, 1.88989786e+06]),
 array([4.29817792e+04, 9.70317644e+02, 1.24900000e+03, 3.32821986e+06]),
 array([8.06633421e+04, 8.76704399e+02, 1.24900000e+03, 8.08335806e+06]),
 array([1.79685619e+05, 9.75654942e+02, 1.24900000e+03, 3.59499062e+07]),
 array([3.74805481e+04, 1.07316672e+03, 1.24900000e+03, 2.66287646e+06]),
 array([6.53069834e+04, 9.48039119e+02, 1.24900000e+03, 6.00052108e+06]),
 array([2.28126638e+04, 9.41021016e+02, 1.24900000e+03, 2.60838612e+06]),
 array([8.12153898e+04, 8.65217193e+02, 1.24900000e+03, 8.15299013e+06]),
 array([7.28248368e+04, 9.88286841e+02, 1.24900000e+03, 6.30067355e+06]),
 array([5.60283045e+04, 7.50389661e+02, 1.24900000e+03, 3.85971778e+06]),
 array([2.86950454e+04, 9.18872142e+02, 1.24900000e+03, 1.29799652e+06]),
 array([ 17954.670359  ,    743.89085125,   1249.        , 494388.56545047]),
 array([ 12895.12073735,    749.0935595 ,   1249.        , 561471.45891089]),
 array([3.03751776e+04, 8.25287595e+02, 1.24900000e+03, 1.43400807e+06]),
 array([2.42300467e+04, 7.16826996e+02, 1.24900000e+03, 1.26148294e+06]),
 array([9.17338663e+04, 9.79684949e+02, 1.24900000e+03, 1.31092824e+07]),
 array([4.60947447e+04, 8.90369029e+02, 1.24900000e+03, 3.68184713e+06]),
 array([4.50878369e+04, 8.99088270e+02, 1.24900000e+03, 2.13629536e+06]),
 array([9.61315640e+04, 1.00939986e+03, 1.24900000e+03, 1.06932943e+07]),
 array([8.00671246e+04, 8.57485036e+02, 1.24900000e+03, 7.47935284e+06]),
 array([7.56895538e+04, 7.93149651e+02, 1.24900000e+03, 6.11741870e+06]),
 array([2.86413656e+04, 8.32290561e+02, 1.24900000e+03, 1.86947412e+06]),
 array([5.36154971e+04, 9.54278379e+02, 1.24900000e+03, 3.43275079e+06]),
 array([2.53285887e+04, 8.95526344e+02, 1.24900000e+03, 1.73055827e+06]),
 array([9.44339222e+04, 8.49864912e+02, 1.24900000e+03, 1.01483932e+07]),
 array([7.41076321e+04, 8.10981582e+02, 1.24900000e+03, 6.39120160e+06]),
 array([1.02420295e+05, 9.66008996e+02, 1.24900000e+03, 1.15854202e+07]),
 array([5.78091188e+04, 9.71075155e+02, 1.24900000e+03, 5.45187169e+06]),
 array([5.12555512e+04, 1.04023433e+03, 1.24900000e+03, 4.27542578e+06]),
 array([1.75217312e+05, 7.05209355e+02, 1.24900000e+03, 3.41322057e+07]),
 array([2.00891572e+05, 7.90267196e+02, 1.24900000e+03, 4.48756187e+07]),
 array([2.09201035e+05, 9.16661938e+02, 1.24900000e+03, 4.99439754e+07]),
 array([2.07845955e+05, 8.28075656e+02, 1.24900000e+03, 4.79976881e+07]),
 array([1.73073885e+05, 9.03526106e+02, 1.24900000e+03, 2.88650102e+07]),
 array([2.53478201e+05, 8.17098849e+02, 1.24900000e+03, 7.48454666e+07]),
 array([1.65704258e+05, 8.90707791e+02, 1.24900000e+03, 2.12257233e+07]),
 array([1.98018217e+05, 8.96870603e+02, 1.24900000e+03, 4.41443474e+07]),
 array([2.10807183e+05, 8.52084919e+02, 1.24900000e+03, 4.99024638e+07]),
 array([2.39304227e+05, 9.11411114e+02, 1.24900000e+03, 6.52533087e+07]),
 array([1.09698970e+05, 5.77803358e+02, 1.24900000e+03, 1.44579804e+07]),
 array([5.58181213e+04, 6.57612625e+02, 1.24900000e+03, 3.46668416e+06]),
 array([7.28214834e+04, 7.06880484e+02, 1.24900000e+03, 5.92896163e+06]),
 array([5.20866683e+04, 7.05871817e+02, 1.24900000e+03, 2.76633363e+06]),
 array([4.34066059e+04, 7.02324730e+02, 1.24900000e+03, 1.89238206e+06]),
 array([6.37706228e+04, 6.25694268e+02, 1.24900000e+03, 4.61645575e+06]),
 array([5.13752835e+04, 7.15581014e+02, 1.24900000e+03, 2.88986089e+06]),
 array([4.89668964e+04, 7.58178530e+02, 1.24900000e+03, 2.72283557e+06]),
 array([ 11155.801233  ,    664.067441  ,   1249.        , 201426.61099495]),
 array([1.51557517e+05, 7.24549718e+02, 1.24900000e+03, 2.99558820e+07]),
 array([1.38666467e+04, 9.15237593e+02, 1.24900000e+03, 1.50817187e+06]),
 array([1.94987094e+05, 1.16793126e+03, 1.24900000e+03, 4.89563635e+07]),
 array([7.81483776e+04, 1.03236619e+03, 1.24900000e+03, 1.07747009e+07]),
 array([1.90655862e+04, 8.53887649e+02, 1.24900000e+03, 2.11168152e+06]),
 array([3.61326122e+04, 8.14545765e+02, 1.24900000e+03, 2.97770879e+06]),
 array([3.69062309e+04, 8.50931668e+02, 1.24900000e+03, 3.59077356e+06]),
 array([9.38703819e+04, 9.76907463e+02, 1.24900000e+03, 1.06643613e+07]),
 array([3.18341840e+04, 9.54419923e+02, 1.24900000e+03, 2.77665396e+06]),
 array([3.99567813e+04, 9.09251767e+02, 1.24900000e+03, 3.89843097e+06]),
 array([3.86772673e+04, 9.60435078e+02, 1.24900000e+03, 3.54420748e+06]),
 array([3.39602575e+04, 8.20957476e+02, 1.24900000e+03, 1.69472326e+06]),
 array([ 10917.209356  ,    772.97419325,   1249.        , 520324.96959596]),
 array([2.45069626e+04, 8.80299534e+02, 1.24900000e+03, 1.85362279e+06]),
 array([1.79295226e+04, 7.22798638e+02, 1.24900000e+03, 1.64359794e+06]),
 array([5.00546861e+04, 7.89489340e+02, 1.24900000e+03, 3.93278361e+06]),
 array([2.56095669e+04, 8.73581414e+02, 1.24900000e+03, 2.31993542e+06]),
 array([1.93173646e+04, 8.59252506e+02, 1.24900000e+03, 1.81384270e+06]),
 array([3.71169239e+04, 8.36520173e+02, 1.24900000e+03, 2.42057219e+06]),
 array([1.67417268e+04, 8.77396398e+02, 1.24900000e+03, 1.51675223e+06]),
 array([1.51608456e+04, 8.25539133e+02, 1.24900000e+03, 1.50307045e+06]),
 array([2.01134870e+04, 1.13781570e+03, 1.24900000e+03, 2.46490654e+06]),
 array([2.62636284e+04, 1.15310860e+03, 1.24900000e+03, 2.61065795e+06]),
 array([2.11020718e+04, 1.17309539e+03, 1.24900000e+03, 2.43746194e+06]),
 array([2.17915503e+04, 1.14797193e+03, 1.24900000e+03, 2.46508622e+06]),
 array([2.83477532e+04, 1.18404313e+03, 1.24900000e+03, 2.50253929e+06]),
 array([4.41683055e+04, 1.19204769e+03, 1.24900000e+03, 3.49818341e+06]),
 array([2.35765780e+04, 1.21596471e+03, 1.24900000e+03, 2.76113035e+06]),
 array([6.91078339e+04, 1.32233208e+03, 1.24900000e+03, 7.91338120e+06]),
 array([3.82796499e+04, 1.23971588e+03, 1.24900000e+03, 4.03238438e+06]),
 array([1.23910352e+05, 1.43807970e+03, 1.24900000e+03, 1.95357206e+07]),
 array([2.83514994e+04, 1.19329978e+03, 1.24900000e+03, 3.52585639e+06]),
 array([2.86598219e+04, 1.18654449e+03, 1.24900000e+03, 2.89642568e+06]),
 array([7.70596862e+04, 1.12209186e+03, 1.24900000e+03, 6.93678375e+06]),
 array([8.67799388e+04, 1.29328829e+03, 1.24900000e+03, 8.23574418e+06]),
 array([3.85199508e+04, 1.06776263e+03, 1.24900000e+03, 2.48207994e+06]),
 array([5.20383371e+04, 1.12574756e+03, 1.24900000e+03, 4.22794976e+06]),
 array([3.22780538e+04, 1.08922869e+03, 1.24900000e+03, 2.77874901e+06]),
 array([7.19595328e+04, 1.21520719e+03, 1.24900000e+03, 6.02928361e+06]),
 array([4.08288919e+04, 1.32095152e+03, 1.24900000e+03, 5.04003120e+06]),
 array([3.06295513e+04, 1.30235009e+03, 1.24900000e+03, 3.17449373e+06]),
 array([7.19938981e+04, 1.37635304e+03, 1.24900000e+03, 7.60772663e+06]),
 array([ 10694.216328  ,   1128.37271675,   1249.        , 806363.04263184]),
 array([8.28308682e+04, 7.74298541e+02, 1.24900000e+03, 8.64172319e+06]),
 array([2.46733519e+04, 8.94912570e+02, 1.24900000e+03, 1.56096372e+06]),
 array([7.29413808e+04, 1.12304034e+03, 1.24900000e+03, 7.68359284e+06]),
 array([4.20037320e+04, 1.21134757e+03, 1.24900000e+03, 4.04383364e+06]),
 array([7.91476026e+04, 1.17675820e+03, 1.24900000e+03, 8.95850309e+06]),
 array([5.38944707e+04, 9.60364199e+02, 1.24900000e+03, 4.41422027e+06]),
 array([1.47334275e+05, 9.02751994e+02, 1.24900000e+03, 3.04321923e+07]),
 array([2.05348410e+04, 1.21287820e+03, 1.24900000e+03, 1.88684162e+06]),
 array([1.52936796e+04, 1.35800886e+03, 1.24900000e+03, 3.22269376e+06]),
 array([3.46218583e+04, 1.34036090e+03, 1.24900000e+03, 4.14670753e+06]),
 array([3.03866699e+04, 1.39058628e+03, 1.24900000e+03, 5.53712718e+06]),
 array([6.32937086e+04, 1.32304782e+03, 1.24900000e+03, 9.96870056e+06]),
 array([1.55241729e+04, 1.23823994e+03, 1.24900000e+03, 1.95299035e+06]),
 array([7.36184261e+04, 1.27654468e+03, 1.24900000e+03, 9.61255357e+06]),
 array([9.82665689e+04, 1.27146832e+03, 1.24900000e+03, 1.45759163e+07]),
 array([7.83647975e+04, 1.28190482e+03, 1.24900000e+03, 1.23911073e+07]),
 array([ 10175.663373 ,   1020.5461   ,   1249.       , 957532.5545316]),
 array([4.40834866e+04, 1.29482471e+03, 1.24900000e+03, 4.61096359e+06]),
 array([9.57439713e+04, 6.65632793e+02, 1.24900000e+03, 1.55976894e+07]),
 array([  9244.974422  ,    751.25515225,   1249.        , 231933.97429888]),
 array([8.17029042e+05, 1.97546886e+03, 1.24900000e+03, 8.29400166e+08]),
 array([4.30629975e+04, 5.05028679e+02, 1.24900000e+03, 3.42104598e+06]),
 array([4.37127431e+05, 9.32526025e+02, 1.24900000e+03, 2.43434580e+08]),
 array([6.02447236e+04, 5.57564959e+02, 1.24900000e+03, 6.16987932e+06]),
 array([5.22865664e+05, 1.27691100e+03, 1.24900000e+03, 3.27849918e+08]),
 array([5.62692749e+05, 1.50801709e+03, 1.24900000e+03, 3.95763982e+08]),
 array([6.14651517e+05, 1.93334315e+03, 1.24900000e+03, 4.67169715e+08]),
 array([6.86739110e+04, 5.45395900e+02, 1.24900000e+03, 7.03719791e+06]),
 array([4.50419427e+04, 8.79516215e+02, 1.24900000e+03, 3.33124374e+06]),
 array([7.67640036e+04, 9.39498959e+02, 1.24900000e+03, 5.96021304e+06]),
 array([1.00467306e+05, 1.23705544e+03, 1.24900000e+03, 1.54333615e+07]),
 array([3.20239369e+04, 8.57639558e+02, 1.24900000e+03, 3.68719672e+06]),
 array([6.48748170e+05, 1.99947647e+03, 1.24900000e+03, 4.75466817e+08]),
 array([1.62538923e+05, 1.04411180e+03, 1.24900000e+03, 3.78104398e+07]),
 array([9.13040788e+04, 1.03549572e+03, 1.24900000e+03, 1.77124740e+07]),
 array([2.95088546e+04, 9.58889469e+02, 1.24900000e+03, 3.54162200e+06]),
 array([1.44756699e+05, 1.21971607e+03, 1.24900000e+03, 3.25264780e+07]),
 array([6.40008664e+04, 8.85494736e+02, 1.24900000e+03, 8.71913046e+06]),
 array([6.29578742e+04, 8.68756969e+02, 1.24900000e+03, 7.87089621e+06]),
 array([3.23816280e+04, 9.30430492e+02, 1.24900000e+03, 4.79187321e+06]),
 array([1.31059353e+05, 9.40538281e+02, 1.24900000e+03, 1.77768478e+07]),
 array([9.71369700e+04, 1.45890288e+03, 1.24900000e+03, 1.62834782e+07]),
 array([1.30245906e+05, 1.07614758e+03, 1.24900000e+03, 1.91633060e+07]),
 array([2.02192814e+05, 1.13551600e+03, 1.24900000e+03, 4.29282103e+07]),
 array([4.55423349e+04, 1.20716229e+03, 1.24900000e+03, 4.39318868e+06]),
 array([9.45170898e+05, 2.19409759e+03, 1.24900000e+03, 1.03047909e+09]),

In [53]:
y_train

[np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(9),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12),
 np.int64(12)]

In [54]:
x_test, y_test = separar_x_y(dataset_exemplo_teste)

### Treinando modelo

Normalizando os dados

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

ValueError: Found array with 0 feature(s) (shape=(362, 0)) while a minimum of 1 is required by StandardScaler.

Criando e treinando modelo

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

KNeighborsClassifier()

Realizando predições

In [40]:
y_pred = knn.predict(x_test)
y_pred

ValueError: Found array with 0 feature(s) (shape=(362, 0)) while a minimum of 1 is required by KNeighborsClassifier.

Avaliando modelo

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
acuracia = accuracy_score(y_test, y_pred)
acuracia