# Experimentos

## Importando requisitos

In [17]:
import pandas
import os

## Abrindo a planilha

In [4]:
planilha = pandas.read_csv('../Dataset/DataSummary.csv')
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
0,1,Image,Adiac,390,391,37,176,0.3887,0.3913 (3),0.3964,0.9591,A. Jalba
1,2,Image,ArrowHead,36,175,3,251,0.2000,0.2000 (0),0.2971,0.6057,L. Ye & E. Keogh
2,3,Spectro,Beef,30,30,5,470,0.3333,0.3333 (0),0.3667,0.8000,K. Kemsley & A. Bagnall
3,4,Image,BeetleFly,20,20,2,512,0.2500,0.3000 (7),0.3000,0.5000,J. Hills & A. Bagnall
4,5,Image,BirdChicken,20,20,2,512,0.4500,0.3000 (6),0.2500,0.5000,J. Hills & A. Bagnall
...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Filtrando na planilha os datasets selecionados

In [9]:
planilha = planilha[planilha['ID'].between(97, 128)]
planilha

,ID,Type,Name,Train,Test,Class,Length,ED (w=0),DTW (learned_w),DTW (w=100),Default rate,Data donor/editor
96,97,EOG,EOGVerticalSignal,362,362,12,1250,0.5580,0.5249 (2),0.5525,0.9144,E. Keogh & H. A. Dau
97,98,Spectro,EthanolLevel,504,500,4,1751,0.7260,0.7180 (1),0.7240,0.7480,A. Bagnall
98,99,Sensor,FreezerRegularTrain,150,2850,2,301,0.1951,0.0930 (1),0.1011,0.5000,REFIT project
99,100,Sensor,FreezerSmallTrain,28,2850,2,301,0.3242,0.3242 (0),0.2411,0.5000,REFIT project
100,101,HRM,Fungi,18,186,18,201,0.1774,0.1774 (0),0.1613,0.8978,W. Fonzi
101,102,Trajectory,GestureMidAirD1,208,130,26,Vary,0.4231,0.3615 (5),0.4308,0.9615,H. A. Dau
102,103,Trajectory,GestureMidAirD2,208,130,26,Vary,0.5077,0.4000 (6),0.3923,0.9615,H. A. Dau
103,104,Trajectory,GestureMidAirD3,208,130,26,Vary,0.6538,0.6231 (1),0.6769,0.9615,H. A. Dau
104,105,Sensor,GesturePebbleZ1,132,172,6,Vary,0.2674,0.1744 (2),0.2093,0.8140,I. Maglogiannis
105,106,Sensor,GesturePebbleZ2,146,158,6,Vary,0.3291,0.2215 (6),0.3291,0.8101,I. Maglogiannis
106,107,Motion,GunPointAgeSpan,135,316,2,150,0.1013,0.0348 (3),0.0823,0.4937,A. Ratanamahatana & E. Keogh
107,108,Motion,GunPointMaleVersusFemale,135,316,2,150,0.0253,0.0253 (0),0.0032,0.4747,A. Ratanamahatana & E. Keogh
108,109,Motion,GunPointOldVersusYoung,136,315,2,150,0.0476,0.0349 (4),0.1619,0.4762,A. Ratanamahatana & E. Keogh
109,110,Device,HouseTwenty,40,119,2,2000,0.3361,0.0588 (33),0.0756,0.4202,E. Keogh & S. Gharghabi
110,111,EPG,InsectEPGRegularTrain,62,249,3,601,0.3213,0.1727 (11),0.1285,0.5261,E. Keogh & S. Gharghabi
111,112,EPG,InsectEPGSmallTrain,17,249,3,601,0.3373,0.3052 (1),0.2651,0.5261,E. Keogh & S. Gharghabi
112,113,Traffic,MelbournePedestrian,1194,2439,10,24,0.1525,0.1845 (1),0.2091,0.8995,H.A. Dau
113,114,Image,MixedShapesRegularTrain,500,2425,5,1024,0.1027,0.0911 (4),0.1584,0.7303,E. Keogh
114,115,Image,MixedShapesSmallTrain,100,2425,5,1024,0.1645,0.1674 (7),0.2202,0.7303,E. Keogh
115,116,Sensor,PickupGestureWiimoteZ,50,50,10,Vary,0.4400,0.3400 (17),0.3400,0.9000,J. Guna
116,117,Hemodynamics,PigAirwayPressure,104,208,52,2000,0.9423,0.9038 (1),0.8942,0.9808,M. Guillame-Bert
117,118,Hemodynamics,PigArtPressure,104,208,52,2000,0.8750,0.8029 (1),0.7548,0.9808,M. Guillame-Bert
118,119,Hemodynamics,PigCVP,104,208,52,2000,0.9183,0.8413 (11),0.8462,0.9808,M. Guillame-Bert
119,120,Device,PLAID,537,537,11,Vary,0.4767,0.1657 (12),0.1639,0.8380,P. Schafer
120,121,Power,PowerCons,180,180,2,144,0.0667,0.0778 (3),0.1222,0.5000,"EDF R&D, France"
121,122,Spectrum,Rock,20,50,4,2844,0.1600,0.1600 (0),0.4000,0.5800,Y. Zhu
122,123,Spectrum,SemgHandGenderCh2,300,600,2,1500,0.2383,0.1550 (1),0.1983,0.3500,C.-C. M. Yeh
123,124,Spectrum,SemgHandMovementCh2,450,450,6,1500,0.6311,0.3622 (1),0.4156,0.8333,C.-C. M. Yeh
124,125,Spectrum,SemgHandSubjectCh2,450,450,5,1500,0.5956,0.2000 (3),0.2733,0.8000,C.-C. M. Yeh
125,126,Sensor,ShakeGestureWiimoteZ,50,50,10,Vary,0.4000,0.1600 (6),0.1400,0.9000,J. Guna
126,127,Simulated,SmoothSubspace,150,150,3,15,0.0933,0.0533 (1),0.1733,0.6667,X. Huang
127,128,Simulated,UMD,36,144,3,150,0.2361,0.0278 (6),0.0069,0.6667,Joseph Fourier University

## Realizando experimentos no dataset da primeira linha da tabela

Obtendo o caminho do dataset de exemplo

In [16]:
dataset_exemplo = planilha.iloc[0]['Name']
dataset_exemplo

'EOGVerticalSignal'

In [19]:
dataset_dirname = os.path.join('../Dataset/UCRArchive_2018', dataset_exemplo)
dataset_dirname

'../Dataset/UCRArchive_2018/EOGVerticalSignal'

In [21]:
caminho_arquivo_treino = os.path.join(dataset_dirname, '{}_TRAIN.tsv'.format(dataset_exemplo))
caminho_arquivo_treino

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TRAIN.tsv'

In [22]:
caminho_arquivo_teste = os.path.join(dataset_dirname, '{}_TEST.tsv'.format((dataset_exemplo)))
caminho_arquivo_teste

'../Dataset/UCRArchive_2018/EOGVerticalSignal/EOGVerticalSignal_TEST.tsv'

Abrindo datasets

In [25]:
dataset_exemplo_treino = pandas.read_csv(caminho_arquivo_treino, sep='\t')
dataset_exemplo_treino

,1,-5.7032,-5.8955,-5.8878,-6.08,-6.1723,-6.2646,-6.2568,-6.1491,-6.4414,...,-113.31,-113.41,-113.5,-114.39,-114.48.1,-113.77,-113.07,-113.16,-112.85,-112.94
0,1,-2.18020,-2.30860,-2.33690,-2.36520,-2.39360,-2.02190,-2.0502,-2.0786,-2.5069,...,108.3900,108.5600,108.53000,108.500000,108.4700,108.45000,108.4200,108.3900,108.1600,108.1300
1,1,6.70950,6.52680,6.34420,6.16160,5.97900,5.79640,5.6137,4.5311,2.7485,...,-34.9360,-35.1190,-35.30100,-35.484000,-35.6660,-34.94900,-35.1320,-35.3140,-34.5970,-34.7800
2,1,-0.91251,-0.72238,-0.53226,-0.74213,-0.95201,-1.16190,-1.5718,-1.7816,-1.1915,...,-173.8600,-174.0700,-173.68000,-173.890000,-174.7000,-174.71000,-174.9200,-175.1300,-174.7400,-174.3500
3,1,-5.44400,-5.32610,-4.10820,-3.69020,-3.57230,-3.45440,-3.0364,-2.6185,-2.5006,...,2.0864,1.8044,1.92230,2.040200,2.1582,2.27610,2.3940,2.5119,2.6299,2.7478
4,1,-29.20700,-28.57400,-28.24100,-28.10700,-27.17400,-25.94100,-25.8080,-25.0750,-24.6420,...,105.3000,105.0300,103.97000,103.700000,103.4300,103.17000,102.9000,102.6300,102.3600,102.9000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,12,-4.32250,-2.52830,-2.83410,-2.83980,-2.84560,-2.85130,-4.3571,-4.3629,-4.3686,...,-2.1725,-1.3783,-0.08404,-0.089806,1.5044,-0.10134,-1.1071,-1.1129,-1.3186,-1.3244
357,12,-5.91600,-5.90050,-6.68500,-7.76950,-7.75400,-7.73850,-6.6230,-6.6075,-6.5920,...,32.0100,28.3260,25.44100,27.857000,32.0720,32.08800,31.9030,27.9190,27.9340,27.9500
358,12,2.66670,2.60940,2.55220,4.59490,1.63760,0.38033,2.4231,4.0658,2.3085,...,-42.8540,-42.9110,-42.96900,-43.026000,-44.3830,-45.84000,-44.4980,-44.5550,-44.6120,-47.1690
359,12,-1.22680,-1.24790,1.63100,1.50990,1.38880,3.16770,3.0465,2.9254,3.4043,...,-97.5090,-94.3310,-97.75200,-94.573000,-94.6940,-94.81500,-94.9360,-98.0570,-102.5800,-102.7000
360,12,-11.76000,-9.95780,-12.15500,-12.25300,-10.25000,-12.74800,-10.4450,-12.1430,-11.8400,...,-100.6800,-100.7800,-100.07000,-100.170000,-101.0700,-100.37000,-100.4600,-101.3600,-101.4600,-100.7600

In [24]:
dataset_exemplo_teste = pandas.read_csv(caminho_arquivo_teste, sep='\t')
dataset_exemplo_teste

,1,2.6752,2.6893,3.2034,4.0175,3.9315,3.9456,3.5597,3.8738,3.4879,...,-394.47,-392.45,-391.24,-390.83,-390.71,-390.9,-390.98,-390.87,-390.85,-390.74
0,1,6.84840,6.17140,5.6944,5.31730,5.14030,4.96330,4.18620,3.60920,2.73220,...,-145.6700,-144.8500,-144.2200,-143.900,-143.6800,-143.8600,-143.5300,-144.2100,-144.7900,-144.9600
1,1,-4.91380,-4.87180,-4.8298,-4.98790,-5.14590,-4.50390,-4.66190,-3.72000,-3.57800,...,-169.2700,-169.4300,-169.5900,-169.140,-169.1000,-169.2600,-169.4200,-169.9800,-170.7300,-170.8900
2,1,18.27800,18.29000,18.3020,18.31400,18.32600,19.13800,19.15000,19.86200,19.17400,...,308.3300,307.8400,308.3500,307.670,307.3800,308.2900,308.3000,308.3100,307.8300,307.8400
3,1,-6.26350,-6.28940,-6.0153,-5.34120,-5.46710,-6.09300,-6.71890,-6.34470,-6.47060,...,39.2290,38.5030,38.0770,37.551,37.4250,36.4990,36.3740,37.0480,36.9220,36.7960
4,1,-2.90750,-3.43210,-3.5567,-4.78130,-4.90590,-5.03040,-5.15500,-4.17960,-3.60420,...,-8.5853,-8.7098,-8.9344,-9.359,-9.4836,-9.6082,-9.4327,-9.2573,-8.6819,-7.9065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,12,2.02960,1.62900,1.2284,0.92786,0.72729,0.42672,0.42615,0.12558,0.12501,...,-12.3750,-14.5760,-14.5760,-12.577,-12.5770,-11.2780,-11.2790,-12.5790,-11.2800,-12.5800
357,12,1.39790,1.59650,1.6951,0.89369,1.09230,1.29090,0.28948,0.08808,0.28668,...,132.6600,132.4600,132.6600,132.850,133.4500,133.9500,133.8500,134.0500,133.8500,134.3500
358,12,1.90450,1.74240,1.8803,3.41830,2.15620,1.99420,2.13210,3.97010,4.10800,...,93.1540,92.9920,92.6300,92.068,90.6060,89.7440,89.2820,89.0200,88.7580,88.8960
359,12,17.80400,16.97900,16.5540,16.02900,15.70400,15.07800,14.75300,13.22800,11.50300,...,-419.6600,-419.9900,-420.3100,-420.040,-420.0600,-420.3900,-420.5100,-420.8400,-421.1600,-421.4900
360,12,-0.10837,0.44276,1.4939,2.34500,2.29610,2.94730,2.89840,2.84950,2.10070,...,-103.2100,-103.8600,-103.9100,-103.950,-104.3000,-104.0500,-104.1000,-104.4500,-104.5000,-104.9500